module pending_migrations

import PormG.Migrations
import OrderedCollections: OrderedDict

# table: dim_teste_timezone
dim_teste_timezone = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS dim_teste_timezone (
  "data2" timestamptz NOT NULL,
  "texto" varchar(250) NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY
);""",
 
"Create index on id" =>
 """CREATE INDEX IF NOT EXISTS "dim_teste_timezone_id_ybheeevb_idx" ON "dim_teste_timezone" ("id");""")

end
