module pending_migrations

import PormG.Migrations

# table: Dim_ibge
Dim_ibge = Dict{String, Any}("Plan" => "New model",
 "SQL" => """CREATE TABLE IF NOT EXISTS Dim_ibge (
  "iso" integer NOT NULL,
  "lat" decimal(30, 6) NOT NULL,
  "regiao" varchar(30) NOT NULL,
  "uf" varchar(2) NOT NULL,
  "cod_es" integer NOT NULL,
  "regional" varchar(30) NULL,
  "lng" decimal(30, 6) NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "cidade" varchar(250) NOT NULL,
  "estado" varchar(50) NOT NULL
))""")

# table: Dim_uf
Dim_uf = Dict{String, Any}("Plan" => "New model",
 "SQL" => """CREATE TABLE IF NOT EXISTS Dim_uf (
  "sigla" varchar(2) NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nome" varchar(50) NOT NULL
))""")

# table: Dim_estabelecimento
Dim_estabelecimento = Dict{String, Any}("Plan" => "New model",
 "SQL" => """CREATE TABLE IF NOT EXISTS Dim_estabelecimento (
  "publico" boolean NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nome" varchar(250) NOT NULL,
  "cnes" varchar(250) NOT NULL,
  "hamigo" boolean NOT NULL
))""")

end
