
"build a row to join"
function _determine_join_type(field::PormGField; previus_how::Union{String, Nothing} = nothing, second_fild_name::Union{String, Nothing}=nothing)
  if previus_how !== nothing && previus_how == "LEFT"
    # if the previous join was a LEFT JOIN, the current join must be a LEFT JOIN
    return "LEFT"
  end
  
  @pormg_debug false
  if !hasproperty(field, :how)
    if second_fild_name !== nothing
      _check_if_field_is_a_operator(second_fild_name)
    end
    throw(QueryBuildError("The field '$(field)' does not have a 'how' property"))
  elseif field.how !== nothing && !isempty(field.how)
    return _normalize_join_type(field.how)
  end
  
  return field.null ? "LEFT" : "INNER"
end

"""
    _cache_join(field::String, instruct::SQLInstruction)

Checks if a join path `field` is already in the cache. If not, and it's a join path (contains `__`), 
it attempts to build the join and cache it. Returns `true` if the field is in cache 
(either before or after the attempt), `false` otherwise.
"""
function _cache_join(field::String, instruct::SQLInstruction)
  memo_projection(instruct, memo_key(:base, field)) === nothing || return true

  if contains(field, "__")
    try
      # Build the join and get the SQL selector (e.g., "Tb.column")
      sql_selector = _build_row_join(split(field, "__") |> Vector{String}, instruct)

      # Populate the cache so it can be used immediately
      memo_projection!(instruct, memo_key(:base, field), SQLField(sql_selector, field))   # #474: base-model namespace
      return true
    catch e
      return false
    end
  end
  return false
end

# #45 — materialize a `cjoin_on` entry into a row_join WITHOUT the FK-driven anchor path. The ON
# clause is entirely user-provided (`config.filters`); no `main.key_a = joined.key_b` equi-anchor
# is emitted (`build_row_join_sql_text` dispatches on the row being an `AnchorlessJoin`). The row
# has no key columns, but `_insert_join`'s dedup keys on (a, b, key_a, key_b, alias_a) and NOT
# alias_b — so `_dedup_key` contributes the unique user alias in the `key_a` position, otherwise two
# cjoin_on joins to the same target model would collide and one would be silently dropped.
#
# The row KIND drives RENDERING (skip the equi-anchor, #435's relocation diagnosis, the
# correlated-UPDATE refusal), which is a different question from which namespace the config came
# from. #484 removed the CONFIG-level tag — `AliasJoin`'s type and its map answer that — and #487
# removed the row-level `"no_anchor" => "1"` string flag that used to answer this one.
function _build_cjoin_on_row_join(config::AliasJoin, user_alias::String, instruct::SQLInstruction)::Nothing
  # #487: the kind IS the marker — `AnchorlessJoin` is what `build_row_join_sql_text` and
  # `_get_join_condition_list` dispatch on. The dedup discriminator the dict row used to carry in
  # `key_a` (the user alias, never rendered) is what `_dedup_key` contributes for this kind.
  row_join = AnchorlessJoin(
    a       = Models.model_table_name(instruct.object.model),
    alias_a = instruct.alias,
    b       = Models.model_table_name(config.target),
    alias_b = user_alias,
    how     = config.join_type,
    on_conditions = config.filters,
  )
  # #488 — fail closed on a target registered on a connection this statement does not run on. The
  # statement's connection is what `get_settings` resolves: the `.db("key")` override first, then the
  # base model's registration — never the target's, so a join to a model from another connection
  # would render a table that lives in a different database and nothing downstream would notice.
  # Checked HERE, where that resolution is final (`.db()` may follow the `cjoin_on` call), and only
  # when both sides are registered: an unregistered target (`connect_key === nothing`) is not judged,
  # and the model-NAME spelling can only ever produce a same-module model.
  query_key = instruct.object.connect_key !== nothing ? instruct.object.connect_key : instruct.object.model.connect_key
  target_key = config.target.connect_key
  if query_key !== nothing && target_key !== nothing && target_key != query_key
    throw(QueryBuildError("cjoin_on target model '$(row_join.b)' (alias \"$(user_alias)\") is registered on connection " *
      "'$(target_key)', but this query runs on '$(query_key)'. A join cannot cross connections; " *
      "pass a model registered on the connection the query runs on."))
  end
  # #480 — fail closed on a range variable the statement already has. `_get_alias_name` now steps
  # around every declared `cjoin_on` alias, so a GENERATED alias can no longer take this one; what
  # is left is the base relation's own alias (`instruct.alias`, never generated by that function)
  # and any producer that bypassed it. Both would render two `AS "<alias>"` in one FROM list —
  # invalid SQL, or an ON clause and a projection that silently name different relations.
  holder = user_alias == instruct.alias ? row_join.a : nothing
  if holder === nothing
    for r in instruct.row_join
      if r.alias_a == user_alias || r.alias_b == user_alias
        holder = r.b
        break
      end
    end
  end
  if holder !== nothing
    throw(QueryBuildError(
      "cjoin_on alias \"$(user_alias)\" is already the alias of \"$(holder)\" in this statement; " *
      "two range variables cannot share a name. Choose another alias."))
  end
  # #484 — `track_path = false`: an alias is not a join path, so it must not claim a name in
  # `row_path`, which is the PATH loop's membership set. Same argument #474 made for a CTE hop.
  _insert_join(instruct.row_join, row_join, instruct.row_path, user_alias; track_path = false)
  return nothing
end

function _build_row_join(field::Vector{SubString{String}}, instruct::SQLInstruction; as::Bool=true, cte::Bool=false)
  # convert the field to a vector of string
  vector = String.(field)
  _build_row_join(vector, instruct, as=as, cte=cte)
end

# Resolve one join-path segment to the field that actually carries the relation, so a Django-style
# `driver__forename` reaches the FK column `driver_id`.
#
# #345 removed the `instruct.django === nothing && return field_name` gate that used to sit on top.
# It made this conditional on `Settings.django_prefix`, a **table-naming** option — the same "a naming
# flag silently switches behaviour on" shape #344 removed from sequence syncing, and worse here,
# because #345 is precisely the change that stops anyone needing the prefix for naming. Unsetting it
# turned working Django-style join paths into `UnknownFieldError`s, with nothing in the message
# pointing at the setting.
#
# The prefix was never needed for this to be correct: the `_id` convention lives on the MODEL, which
# is what the lookups below read. Ungating is additive for a prefix-less connection — every branch
# below is reached only when the segment resolves to nothing on its own, so a path that worked before
# still resolves the same way and one that used to throw a few frames later now joins. It is NOT
# universally additive: see the `related_objects` guard below, which is where the one behaviour change
# for PREFIXED connections is described.
#
# #345 also DELETED the rejection of the explicit `driver_id__forename` spelling that lived here.
# That was a style rule, not a correctness one — both spellings render identical SQL — and it was
# only ever enforced for prefixed connections. Making it universal broke `cjoin`, whose key must be
# in `model.field_names` and is therefore necessarily the `_id` column (`ctes.jl`), and
# `PormGRow.save()`, which splits a projected key on `__` and looks the prefix up verbatim in
# `model.fields` — so the short form it recommended raises `KeyError` on the write path. PormG's own
# `test/integration/test_row_mutation.jl` uses the explicit spelling. There is no spelling that
# satisfies both paths, which is the tell that the rule was wrong rather than the call sites.
#
# `instruct` went with the gate — it was the only thing this function read it for.
function _resolve_fk_short_form(model::PormGModel, field_name::String)::String
  # The field exists directly — including the explicit `<fk>_id` form, which resolves to itself.
  # Single O(1) dict lookup replaces the previous O(n) vector scan + dict access.
  haskey(model.fields, field_name) && return field_name

  # An EXPLICIT relation claims the name, so the implicit rewrite defers to it (#345).
  #
  # `_build_row_join` tries the forward-FK branch on the RESOLVED column and the reverse branch on
  # the RAW segment, in that order. So rewriting `x` to `x_id` here when `x` is also a reverse
  # accessor moves the path from one branch to the other: a different table, joined on a different
  # column, with no error. Take a model with FK `circuit_id` and a child declaring
  # `related_name = "circuit"` — `circuit__name` means the child, in reverse.
  #
  # This is a genuine ambiguity that PormG has to resolve one way, and it resolved it BOTH ways
  # before #345, depending on a table-naming option: prefix-less connections read the reverse
  # relation (the gate returned early), prefixed ones read the forward FK (resolution ran). The rule
  # is now the same for everyone, and it is the one that keeps an author's explicit declaration
  # authoritative: `related_name = "circuit"` is a name someone chose, while `circuit` -> `circuit_id`
  # is a convenience this function invents. An invented name must not displace a declared one.
  #
  # Do NOT reach for Django's `fields.E302` to argue the clash is already ill-formed — it is not, for
  # PormG. E302 compares a reverse accessor against the target's FIELD names, and a Django FK spelled
  # `driver` IS the field `driver`, so it collides. A PormG-native model declares that FK as
  # `driver_id`, which `driver` does not collide with, so the model set is perfectly legal here.
  # `test/unit/test_complex_queries.jl`'s `FkShortFormModels` is exactly such a set.
  haskey(model.related_objects, field_name) && return field_name

  # Short-form resolution: "driver" → "driver_id" when a FK with that name exists.
  # This only applies to snake_case FK convention (e.g. driver_id).
  # camelCase FKs (e.g. driverid) must be referenced by their full field name.
  fk_field = get(model.fields, field_name * "_id", nothing)
  if fk_field !== nothing && hasfield(typeof(fk_field), :to)
    return field_name * "_id"
  end

  return field_name
end

# Resolve one side of an M2M relation (owner or related) to its PormGModel within `_module`:
# by binding first, then by formatted model name. Lets the join builder read each side's
# `db_column` for its PK (#64) — the relation stores only string names/bindings.
function _resolve_m2m_side_model(_module::Module, binding::String, model_name::String, field_name::String)::PormGModel
  bsym = Symbol(binding)
  if isdefined(_module, bsym)
    candidate = Base.invokelatest(getfield, _module, bsym)
    candidate isa PormGModel && return candidate
  end

  target_name = Models.format_model_name(model_name)
  for model in Models.get_all_models(_module)
    Models.format_model_name(model.name) == target_name && return model
  end

  throw(QueryBuildError("The many-to-many model $(binding) for accessor $(field_name) is not defined"))
end

function _resolve_many_to_many_related_model(_module::Module, relation::Models.ManyToManyRelation)::PormGModel
  return _resolve_m2m_side_model(_module, relation.related_binding, relation.related_model, relation.field_name)
end

function _insert_many_to_many_joins(
  relation::Models.ManyToManyRelation,
  instruct::SQLInstruction,
  parent_table::String,
  parent_alias::String,
  join_path::String;
  previus_how::Union{String, Nothing}=nothing,
  track_path::Bool=true,
)
  join_type = previus_how == "LEFT" ? "LEFT" : "INNER"

  # #64: the PARENT-side join keys (owner_pk / related_pk) are field NAMES; resolve each to
  # its physical column via the owning model's db_column. `model_column` is a strict no-op when the
  # PK has no db_column.
  #
  # The through-table columns (owner_column / related_column) go in as-is, and since #377 that is a
  # claim about the SLOT, not a bet about the model. Both are resolved to physical columns once, at
  # registration, exactly as `through_table` is one line below: on the AUTO path they are names PormG
  # generated for a table PormG created, and on an explicit `through=` they are
  # `Models.model_column(through_model, <the FK field name>)`.
  #
  # Before that they were the through model's FIELD NAME, rendered raw — equal to the physical column
  # exactly when the field declared no `db_column`. Django's default convention satisfies that
  # (`driver` imports as the field `driver_id`, which is also Django's column), which is why an
  # ordinary import joined correctly and the bug survived; a `db_column=` written in the Django source
  # did not, because the importer splats it onto the field it builds (`process_class_fields!`). The
  # shape was origin-independent — hand-written models reached it the same way.
  _module = instruct.object.model._module::Module
  owner_model = _resolve_m2m_side_model(_module, relation.owner_binding, relation.owner_model, relation.field_name)
  related_model = _resolve_m2m_side_model(_module, relation.related_binding, relation.related_model, relation.field_name)

  through_row = ModelJoin(
    a = parent_table,
    alias_a = parent_alias,
    key_a = Models.model_column(owner_model, relation.owner_pk),
    # #363: the through side's PHYSICAL table. This slot carried the through model's LOGICAL name
    # whenever the relation came from an explicit `through=`, so a through model with a `db_table`
    # joined against a table that does not exist. `through_table` is resolved once, at registration.
    b = relation.through_table,
    alias_b = _get_alias_name(instruct),
    key_b = relation.owner_column,
    how = join_type,
  )

  through_alias = _insert_join(instruct.row_join, through_row, instruct.row_path, "$(join_path)__through"; track_path=track_path)

  # `to_many` is NOT set here (#487): `_apply_many_to_many_branch` stamps it onto whichever row
  # SURVIVES dedup for this alias, which is not always this one.
  related_row = ModelJoin(
    a = relation.through_table,
    alias_a = through_alias,
    key_a = relation.related_column,
    # The related side's PHYSICAL table (db_table when set, #59). Unlike `through_table` above,
    # `relation.related_model` carries the LOGICAL name — that is what identifies the model — so this
    # slot, which is rendered as a table, has to go through `model_table_name`.
    b = Models.model_table_name(related_model),
    alias_b = _get_alias_name(instruct),
    key_b = Models.model_column(related_model, relation.related_pk),
    how = join_type,
  )

  return _insert_join(instruct.row_join, related_row, instruct.row_path, join_path; track_path=track_path)
end

# #74 / #487: stamp `to_many` onto the row that SURVIVED dedup for `alias` — which may be a row an
# earlier, hand-written traversal of the same through table produced rather than the one the M2M
# expansion just built — by replacing its slot in `row_join`. A constructor flag on the M2M related
# row would be dropped whenever dedup keeps the earlier row, so the stamp stays a post-insert write,
# now by copy. Returns the stamped row.
function _flag_to_many!(row_join::Vector{JoinRow}, alias::String)::ModelJoin
  i = findfirst(r -> r.alias_b == alias, row_join)
  row = i === nothing ? nothing : row_join[i]
  # Both halves are internal invariants (aliases are minted from the same vector that is searched,
  # and a CTE row shares a model row's dedup key only when a CTE is named after a table, which
  # `_with` refuses — #479). One untyped `error`, because the drift guard counts them per file.
  row isa ModelJoin || error(_emsg("PormG internal error: join alias $(alias) " *
    (row === nothing ? "was not found in row_join" : "resolved to a $(typeof(row)), not a model join") *
    " — this should not happen; please report it."))
  row.to_many && return row
  stamped = ModelJoin(a = row.a, alias_a = row.alias_a, key_a = row.key_a,
                      b = row.b, alias_b = row.alias_b, key_b = row.key_b,
                      how = row.how, to_many = true, on_conditions = row.on_conditions)
  row_join[i] = stamped
  return stamped
end

# Physical table for a REVERSE join target (#59). The reverse path reaches its target through
# `related_objects`, which stores the model's LOGICAL name — so the resolved model is the only place
# a `db_table` can be read from, and it must win. Without an override this reproduces the previous
# derivation byte for byte, including the `django_prefix` arm.
#
# That arm used to be the ONLY way a prefixed deployment's table got spelled, because no generated
# model declared one. Since #345 the Django importer pins `db_table` on every model it emits, so a
# regenerated file takes the early return and the arm is dead for it. It stays for the files that
# have not been regenerated, and for a hand-written model on a prefixed connection.
function _reverse_join_table(reverse_model::PormGModel, logical_name::AbstractString, django)::String
  Models.model_has_db_table(reverse_model) && return Models.model_table_name(reverse_model)
  return django !== nothing ? string(django, lowercase(logical_name)) : lowercase(logical_name)
end

# FORWARD FK/O2O join target whose `.to` is still a STRING (#388). `.to` names the target's Julia
# BINDING (#360/#386), never its table, so the only correct move is to resolve the binding in the
# owning models module and read the table off the model — which is exactly what the resolved-`.to`
# arm beside each call site already does, and what the next-hop lookup does one line later.
#
# Both call sites used to `lowercase` the binding into a table name instead. That inverts
# `uppercasefirst`, which is the right inverse only while the binding IS `uppercasefirst(<table>)`:
# a table `2fast` binds as `Col_2fast` and joined `col_2fast`, `driver profile` binds as
# `Driver_profile` and joined `driver_profile`. Neither table exists. It also ignored `db_table`
# outright, so a parent pinned to an explicit table joined the wrong one even when the guess would
# otherwise have inverted cleanly.
#
# The `instruct.django` arm went with it, deliberately. That prefix fallback is documented as the
# spelling for a REVERSE-join target carrying no `db_table` (`docs/src/schema_conventions.md` →
# *`django_prefix` interop*), and the resolved-model arm this now joins has never applied it — so the
# arm only fired when a key happened to reach the String branch, which rendered ONE foreign key as
# two different tables depending on whether `set_models` had resolved its target yet.
#
# Raises rather than returning `nothing`: an unresolvable binding cannot produce a join at all. What
# changes here is the ERROR, not whether there is one — the old code always failed too, just as a
# bare `UndefVarError` from a `getfield`: at this hop when the path had exactly two segments, and
# one iteration later in the `while` loop (`new_object = getfield(…)`) when it had more. Both name a
# Julia symbol rather than the field path the user wrote, which is the part worth fixing.
#
# The genuinely SILENT case was never the unresolvable binding — it was a binding that DOES resolve
# but whose table is not `lowercase(binding)`, which produced a perfectly well-formed `JOIN` against
# the wrong table. Not necessarily a MISSING one: `Driver_Profile` folds to `driver_profile`, which on
# PostgreSQL is a second, real table that may exist and hold someone else's rows — a query that
# returns results, all of them wrong. That is the case the two mixed-case join testsets pin.
function _forward_join_model(to::AbstractString, mod::Module, owner::PormGModel, column::AbstractString)::PormGModel
  model = Models._resolve_target_model(to, mod)
  model isa PormGModel && return model
  throw(QueryBuildError(
    "Invalid field path: the foreign key \e[31m$(column)\e[0m in \e[32m$(owner.name)\e[0m targets " *
    "\e[31m$(to)\e[0m, which is not a model binding in \e[32m$(mod)\e[0m. A ForeignKey `to` string " *
    "names a Julia model binding, not a table, so there is no table to join."))
end

# Shared helper used at the four sites in `_build_row_join` where a many-to-many
# (forward or reverse) hop must be expanded into the through-table + related-table
# join pair. Returns the alias of the related-table join, the row dict for that
# join, the resolved related PormGModel, and (when applicable) the trailing
# `last_field` reference.
function _apply_many_to_many_branch(
  relation::Models.ManyToManyRelation,
  instruct::SQLInstruction,
  parent_table::String,
  parent_alias::String,
  join_path::String,
  vector::Vector{String};
  previus_how::Union{String, Nothing}=nothing,
  reverse::Bool=false,
  track_path::Bool=true,
)
  foreing_table_module = instruct.object.model._module::Module
  foreign_model = _resolve_many_to_many_related_model(foreing_table_module, relation)
  if length(vector) == 1
    msg = reverse ? "many-to-many reverse field" : "many-to-many field"
    throw(QueryBuildError("Invalid field path: $(vector[1]) is a $(msg), you must inform the column to be selected. Example: ...filter(\"$(vector[1])__column\")"))
  end
  # `get(..., nothing)` rather than a raw index (#446). An unknown terminal column used to die here
  # with a bare `KeyError` naming an internal dict lookup. Falling through leaves `last_field`
  # unset and lets `_solve_field` at the end of this function raise the typed `UnknownFieldError`
  # that names the column, the model and its available fields — one message for every hop shape
  # instead of a KeyError here and a good error three lines later.
  last_field = size(vector, 1) == 2 ? get(foreign_model.fields, vector[2], nothing) : nothing
  tb_alias = _insert_many_to_many_joins(relation, instruct, parent_table, parent_alias, join_path, previus_how=previus_how, track_path=track_path)
  # #74: the related table reached through a many-to-many is the "many-side". Flag the (deduped)
  # row_join entry so the fan-out guard can refuse silently-inflated aggregates over base columns.
  row_join = _flag_to_many!(instruct.row_join, tb_alias)
  return (tb_alias, row_join, foreign_model, last_field)
end

# #27: validate JSON path key segments fail-closed. A segment is either a non-negative integer
# (JSON array index) or a safe key (`SAFE_JSON_KEY_PATTERN`). Anything else (spaces, dots, quotes,
# braces, empty) is rejected, so the validated segments are safe to interpolate into the path
# literal. Returns the segments unchanged.
#
# #394: this checks `SAFE_JSON_KEY_PATTERN`, NOT `SAFE_IDENTIFIER_PATTERN`, even though the two
# bodies match today. A segment is interpolated UNQUOTED into a path literal inside a single-quoted
# SQL string (PostgreSQL braces, SQLite `$.a.b`), so unlike a table or column name it has no quoting
# to fall back on and this charset check is the entire guard. Keeping the constants separate is what
# stops a future relaxation of the SQL-identifier rules from silently widening this one.
function _validate_json_key_segments(segments::Vector{String})::Vector{String}
  for seg in segments
    if occursin(r"^\d+$", seg) || occursin(SAFE_JSON_KEY_PATTERN, seg)
      continue
    end
    throw(InvalidValueError("Invalid JSON key segment \e[31m$(seg)\e[0m in a JSON path lookup. Segments must be a non-negative integer (array index) or a simple key (letters, digits, underscore). Keys with spaces, dots, or quotes are not addressable via the `__` path syntax."))
  end
  return segments
end

# #27: render a JSON path lookup (e.g. `payload__driver`, `payload__0__name`) as a TEXT extraction
# on the resolved column. The base field is a non-terminal JSONField, so the trailing segments are
# a value path, not join hops. Records the resolved path in json_lookup_paths (so the filter-render
# branch binds the RHS as plain text) and tab_field_cache (so downstream sees the base field type).
function _render_json_lookup(instruct::SQLInstruction, alias::String, json_field::PormGField,
    field_name::String, key_segments::Vector{String}, full_field::Vector{String};
    cte::Bool=false)::String
  segs = _validate_json_key_segments(key_segments)
  col = string(quote_identifier(alias, instruct.connection), ".",
               safe_column_identifier(Models.field_db_column(json_field, field_name), instruct.connection))
  # #474: both caches below are keyed by the resolved path, so a CTE-rooted lookup namespaces it for
  # the same reason `row_path` does — `CTE("ev", "meta__driver")` and a model path `ev__meta__driver`
  # produce the same string and must not share an entry.
  path = memo_key(cte ? :cte : :base, join(full_field, "__"))
  memo_json_lookup!(instruct, path)
  memo_field!(instruct, path, json_field)
  return Dialect._json_extract_expr(instruct.connection, col, segs)
end

# #68 — ONE forward ForeignKey / OneToOne hop, shared by the first hop and the loop of
# `_build_row_join`. Before this the two sites carried near-identical copies of the same resolution,
# and the `db_column` key half (#50/#64) had to be hand-applied to each — `test_db_column_deep_joins.jl`
# is the regression that could tell the copies apart. What differs between the two callers stays in
# the callers, on purpose: the first hop's `cjoin(field = …)` override decides which field is
# resolved, and the loop's `hasfield(:to)` guard fires BEFORE the join type is derived, so the two
# report a non-FK column with different messages in a different order (#197). `no_target_message`
# is the caller's own wording for a `.to === nothing` field, for the same reason.
#
# `src_table` is passed, never derived from `src_model`: in the loop it is the previous row's `b`,
# which is the CTE NAME on a CTE-rooted path and `_reverse_join_table(...)`'s spelling after a
# reverse hop — neither equals `model_table_name(src_model)`.
#
# Returns the row it BUILT (not the dedup survivor — the loop reads `prev_how`/`prev_b` off it, as
# it always did), the resolved target model, and the terminal field when this is the last hop.
function _forward_fk_hop(instruct::SQLInstruction, src_model::PormGModel, src_table::String,
                         src_alias::String, column::String, field::PormGField, vector::Vector{String};
                         prev_how::Union{String,Nothing}, no_target_message::String)
  # Resolved BEFORE the `.to` check below, on purpose: `_determine_join_type` is what turns
  # `name__contains` into the "did you mean an operator?" hint, and it has to fire first.
  how = _determine_join_type(field, previus_how = prev_how,
                             second_fild_name = size(vector, 1) > 1 ? vector[2] : nothing)
  target = field.to
  target === nothing && throw(QueryBuildError(no_target_message))
  # #388: the two arms are ONE arm now. A String `.to` is the target's binding, so resolving it
  # yields the same model a `set_models`-resolved `.to` already holds, and the table comes off that
  # model either way. Carrying the model forward (matching the reverse hop below, #343) also
  # spares the next hop and `_solve_field` from repeating the binding lookup.
  next_model = target isa PormGModel ? target :
    _forward_join_model(target, instruct.object.model._module::Module, src_model, column)
  last_field = size(vector, 1) == 2 ? get(next_model.fields, vector[2], nothing) : nothing
  row = ModelJoin(
    a = src_table,
    alias_a = src_alias,
    # Local FK column and referenced parent column both honor db_column (#50). When `src_model` is a
    # CTE model this stays correct WITHOUT a branch (#376): its fields carry no db_column, so `key_a`
    # resolves to the projection alias the CTE actually exposes, while `key_b` reads the REAL target
    # model and keeps its physical column — the two halves of the same contract.
    key_a = Models.field_db_column(field, column),
    b = Models.model_table_name(next_model),
    alias_b = _get_alias_name(instruct),
    key_b = Models.fk_target_column(field),
    how = how,
  )
  return (row, next_model, last_field)
end

# #68 — ONE reverse-relation hop, the mirror of `_forward_fk_hop` and shared the same way. The
# `length(vector) == 1` refusal stays in the callers (both have it), and so does the loop-only
# "column not found on the child" check — the first hop deliberately lacks it (its line has been
# commented out since before #343), and the extraction does not change which hop reports what.
function _reverse_hop(instruct::SQLInstruction, src_model::PormGModel, src_table::String,
                      src_alias::String, rel::Models.ReverseRelation, vector::Vector{String};
                      prev_how::Union{String,Nothing})
  # #343: the child model is READ off the relation, never rebuilt from its name. The old
  # `Symbol(uppercasefirst(lowercased_name))` could only ever spell `Xxxxx`, so a binding with an
  # internal capital (Dim_CNES, CustomUser) raised UndefVarError instead of joining.
  reverse_model = rel.model_resolved
  join_field = reverse_model.fields[String(rel.fk_field)]
  how = _determine_join_type(join_field, previus_how = prev_how, second_fild_name = vector[2])
  last_field = size(vector, 1) == 2 ? get(reverse_model.fields, vector[2], nothing) : nothing
  row = ModelJoin(
    a = src_table,
    alias_a = src_alias,
    # Reverse join: key_a is the parent's referenced column, key_b the child's FK
    # column; both honor db_column (resolved in their own model, no-op without it) (#50).
    key_a = Models.model_column(src_model, String(rel.target_pk)),
    # The LOGICAL name goes straight into the table fallback, which is the only thing that ever
    # wanted it — before #343 it was assigned to `foreign_table_name` and then overwritten.
    b = _reverse_join_table(reverse_model, String(rel.model_name), instruct.django),
    alias_b = _get_alias_name(instruct),
    key_b = Models.model_column(reverse_model, String(rel.fk_field)),
    how = how,
    # #74: a reverse foreign key (one-to-many) makes the child table the many-side.
    to_many = true,
  )
  return (row, reverse_model, last_field)
end

# #68 — the shared tail of every non-M2M hop: fold the path's `cjoin` / `on()` config into the row
# (by copy, #487) and insert it. Returns the alias the hop renders under and the row as inserted,
# so the caller's local carries the override the next hop's `prev_how` reads.
#
# #474: `custom_join` is the BASE model's PATH-keyed join-config registry, and a hop only has a
# config to inherit when it is rooted there. A CTE-rooted hop is not — at the first hop `join_path`
# is the CTE NAME, and past it a recomputed `"<cte>__<seg>"` collides with an `on("ev__parent", …)`
# entry whenever the base model also has a relation named `ev`. So the lookups are gated on `cte`,
# and a CTE row admits only the `(nothing, nothing)` that gate passes; its join type comes from the
# `.with(...)` declaration. #484: the registry no longer holds `cjoin_on` entries either, so the same
# gate covers a MODEL hop whose path equals a declared alias — the third instance of this family.
# `track_path = !cte` for the same reason: a CTE hop must not claim its name in `row_path`.
function _finish_hop!(instruct::SQLInstruction, row::JoinRow, join_path::String; cte::Bool)
  join_type_override = cte ? nothing : _get_join_type_override(instruct.object, join_path)
  join_filters = cte ? nothing : _get_join_filters(instruct.object, join_path)
  row = _with_config(row, join_type_override, join_filters)
  alias = _insert_join(instruct.row_join, row, instruct.row_path, join_path; track_path = !cte)
  return (alias, row)
end

function _build_row_join(field::Vector{String}, instruct::SQLInstruction; as::Bool=true, cte::Bool=false)
  vector = copy(field)
  # #68 narrowed this from `Union{String, PormGModel, Nothing}`: every arm stores a resolved model
  # (#388 made the String member unreachable and asked for the narrowing in a change that runs the
  # join integration slice, which this one did), so the `getfield(module, …)` fallback the loop kept
  # for it is gone with it.
  foreign_table_name::Union{PormGModel, Nothing} = nothing
  foreing_table_module::Module = instruct.object.model._module::Module
  # `row_join` is assigned by exactly one arm below — a fresh `JoinRow` per hop (#487).

  @pormg_debug false

  first_column = _resolve_fk_short_form(instruct.object.model, vector[1])
  last_field::Union{Nothing, PormGField} = nothing
  join_path = field[1]
  # The M2M arms insert their own pair of rows (`_apply_many_to_many_branch` folds the tail), so
  # they skip `_finish_hop!` — which also means a `cjoin`/`on()` config keyed on an M2M path is
  # never consulted. Long-standing behavior; #68 preserves it rather than fixing it in passing.
  inserted = false

  # #27: a non-terminal JSON base field is a value extraction (`payload__key`, `payload__0__name`),
  # not a join hop. Fire before the CTE/FK cascade — otherwise `payload` enters the forward-FK
  # branch and crashes in `_determine_join_type` (a JSONField has no `.how`). A TERMINAL JSON field
  # (length == 1) is left to resolve as a plain jsonb column (the target of the containment operators).
  #
  # `!cte` because a CTE-scoped path is resolved against the CTE's own model, not the base model. A
  # CTE named after a base-model JSONField would otherwise be extracted from that field's jsonb.
  if !cte && haskey(instruct.object.model.fields, first_column) &&
     Models.is_json_field(instruct.object.model.fields[first_column]) &&
     length(vector) > 1
    return _render_json_lookup(instruct, instruct.alias,
      instruct.object.model.fields[first_column], first_column, String.(vector[2:end]), field)
  end

  # #444: a CTE is reached here ONLY through `CTE(name, path)`, which sets `cte=true`. It is not
  # discovered by testing `haskey(instruct.object.ctes, vector[1])` on a plain field path.
  #
  # #492 restored the `"<cte>__<col>"` string spelling, and that does NOT re-open this test: the
  # string is resolved into a `CTEReference` upstream, by `_resolve_cte_string_paths!` (`ctes.jl`),
  # which runs once in `build()` when the registry is final. So both spellings arrive here as a
  # handle, and this branch keeps exactly one entry condition. What #444 removed and #492 kept
  # removed is the PRECEDENCE described below — not the string.
  #
  # That test WAS this branch's condition, and it sat ahead of the many-to-many, forward-FK and
  # reverse-relation arms below — so for any first segment naming both a CTE and something on the
  # model, the CTE won and the model's own join was never emitted. Silently: the only signal was the
  # #44 Cartesian warning, which reports an uncorrelated CROSS JOIN rather than a shadowed relation
  # (#431). Splitting the namespaces removes the precedence question entirely rather than answering
  # it — `.with("parent" => …)` and the `parent` ForeignKey now coexist in one query, each
  # addressable, neither shadowing the other.
  if cte
    @pormg_debug false
    cte_name = vector[1]
    # #444: the single point where a `CTE(name, …)` handle is checked against the query's registry.
    # Both render entries (`_get_select_query` / `_get_filter_query`) funnel through here, so neither
    # has to repeat it.
    if !haskey(instruct.object.ctes, cte_name)
      declared = isempty(instruct.object.ctes) ? "none" : join(sort(collect(keys(instruct.object.ctes))), ", ")
      throw(UnknownFieldError(
        "CTE \e[4m\e[31m$(cte_name)\e[0m is not declared on this query; declared CTEs: " *
        "\e[4m\e[32m$(declared)\e[0m. Add it with \e[4m\e[32m.with(\"$(cte_name)\" => subquery)\e[0m."))
    end
    cte_dict = instruct.object.ctes[cte_name]
    # #433: this is NOT an internal invariant, which is what it claimed to be until the #433 audit.
    # `cte_dict["model"]` is written in exactly one place — `_build_cte_custom_model`, reached only
    # from `build_cte_clause`. So a missing "model" means precisely one thing: THIS statement never
    # ran `build_cte_clause`, and therefore emits no `WITH` clause at all. Referencing the CTE would
    # name a relation the statement never declares. That is a property of the statement kind, not a
    # broken invariant, and it is reachable from ordinary user input:
    #
    #     q.with("gv" => sub, join_field = "parent" => "id")
    #     q.filter("gv__code" => "X")
    #     q.update("note" => "n")        # update() never calls build_cte_clause
    #
    # `update()`'s own CTE refusal (#394, `_get_join_condition_list`) cannot catch that, because it
    # inspects `row_join` entries — which this function is in the middle of producing.
    #
    # Guarding HERE rather than at each caller is deliberate. `build()` has SIX call sites and only
    # three render a `WITH`: `execution.jl` `query`/`_count`/`_exists` do; `_update`,
    # `bulk_update` (`execution_bulk.jl`) and `_build_exists_query` (`build_helpers.jl`, which
    # hand-rolls its own SELECT) do not. A per-caller guard would have to be re-added for each
    # future one. This is the single point where the missing render step becomes observable.
    #
    # The message deliberately does NOT name `update()` as the only culprit: `_build_exists_query`
    # is a READ-path renderer that also emits no `WITH`, so "reads render a CTE" would be a lie on
    # that route. It is currently unreachable only because `_guard_no_nested_cte` refuses a nested
    # CTE earlier with a better message — a single-point dependency worth not encoding into text.
    if !haskey(cte_dict, "model")
      throw(QueryBuildError(
        "The CTE \e[4m\e[31m$(cte_name)\e[0m is referenced here, but the statement being built " *
        "emits no \e[4m\e[32mWITH\e[0m clause — so the CTE would never be declared.\n  " *
        "\e[4m\e[32mlist\e[0m / \e[4m\e[32mfirst\e[0m / \e[4m\e[32mcount\e[0m / " *
        "\e[4m\e[32mexists\e[0m render a CTE. \e[4m\e[32mupdate(...)\e[0m and " *
        "\e[4m\e[32mbulk_update(...)\e[0m do not.\n  " *
        "Scope the statement with a plain \e[4m\e[32m.filter(...)\e[0m or a subquery instead of a " *
        "CTE (#433)."))
    end
    cte_model = cte_dict["model"]::PormGModel
    
    # #444: unreachable from user input — `CTE(name, path)` refuses an empty path at construction,
    # with a message that names the call the user wrote. Kept as a fail-closed backstop so a future
    # internal caller passing a one-element vector gets this instead of a KeyError on `vector[2]`.
    length(vector) == 1 && throw(QueryBuildError("CTE reference '$(cte_name)' must include a column path. Example: CTE(\"$(cte_name)\", \"field_name\")"))

    # Get the join field configuration from the CTE
    jf = cte_dict["join_field"]

    if jf === nothing
      # #44: no join_field → the CTE is CROSS JOINed and the correlation is supplied by the
      # main query's `F("<cte>__col")` filter(s), which render verbatim in WHERE. `join_type`
      # does not apply to a CROSS JOIN (INNER-like by nature).
      if !haskey(cte_model.fields, vector[2])
        available = join(collect(keys(cte_model.fields)), ", ")
        throw(UnknownFieldError("CTE field '$(vector[2])' not found in '$(cte_name)'; available fields: $(available)"))
      end
      # #394: a `CrossJoin` IS the marker. A correlated UPDATE ... FROM emits no `WITH` prefix, so a
      # row_join naming a CTE renders `FROM "<cte>" AS "Tb_N"` against a relation the statement
      # never declares; `_get_join_condition_list` refuses both CTE kinds on `_joins_cte`.
      # No key columns: `_dedup_key` contributes empty strings for this kind, which is what dedups
      # repeat references to the same CTE (e.g. r91__raceid, r91__round) onto a single CROSS JOIN,
      # and the CROSS branch of `build_row_join_sql_text` never renders an ON. No join type either:
      # the deep-path loop below reads `_prev_how`, which is `nothing` for this kind, so an
      # over-long path like `F("r91__col__more")` still fails with the keyed path's "not a foreign
      # key" message (#487).
      row_join = CrossJoin(
        a = Models.model_table_name(instruct.object.model),
        alias_a = instruct.alias,
        b = cte_name,  # CTE name becomes the table name
        alias_b = _get_alias_name(instruct),
      )
    else
      join_field_pair = jf::Pair{String, String}
      main_table_key = join_field_pair.first    # e.g., "driverid" from main table
      cte_table_key = join_field_pair.second    # e.g., "driverid" from CTE
      @pormg_debug false

      if !haskey(cte_model.fields, cte_table_key)
        available = join(collect(keys(cte_model.fields)), ", ")
        throw(UnknownFieldError("CTE join_field column '$(cte_table_key)' not found in $(cte_name); available fields: $(available)"))
      end


      if (main_table_key in instruct.object.model.field_names)
        cte_alias_a = instruct.alias
        # #64: resolve the main-model join field to its physical column (db_column).
        cte_key_a = Models.model_column(instruct.object.model, main_table_key)
      elseif memo_projection(instruct, memo_key(:base, main_table_key)) !== nothing || _cache_join(main_table_key, instruct)
        # #474: the MAIN model's join field, so the base-model half of the namespace — never the
        # CTE's, even though this branch sits inside the CTE arm.
        cache_item = memo_projection(instruct, memo_key(:base, main_table_key))
        v_split = split(cache_item.field |> x -> replace(x,  '"' => ""), ".")
        cte_alias_a = v_split[1] |> string
        cte_key_a = v_split[2] |> string
      else
        throw(UnknownFieldError("Main table join_field column '$(main_table_key)' not found in $(instruct.object.model.name); available fields: $(join(instruct.object.model.field_names, ", "))"))
      end

      # Set up the join with the CTE. A `CteJoin` is the #394 marker itself — see the CROSS branch.
      #
      # #64: the CTE side (`key_b`) stays the FIELD NAME — a CTE is a derived table whose columns are
      # the values() projection ALIASES (`"pk_code" AS "code"`), so the join references the
      # alias "code", not the physical column. Only the main-table side (`key_a`) is a
      # real physical column and is db_column-resolved.
      # #376 generalized this from the KEY to every CTE COLUMN, by stripping db_column from the CTE
      # model's fields at construction. So this literal is now also what `Models.model_column(
      # cte_model, cte_table_key)` would answer — kept literal because it needs no lookup.
      row_join = CteJoin(
        a = Models.model_table_name(instruct.object.model),
        alias_a = cte_alias_a,
        key_a = cte_key_a,
        b = cte_name,  # CTE name becomes the table name
        alias_b = _get_alias_name(instruct),
        key_b = cte_table_key,
        how = cte_dict["join_type"]::String,
      )
    end

    @pormg_debug false

    foreign_table_name = cte_model
    last_field = get(cte_model.fields, vector[2], nothing)
   
  elseif haskey(instruct.object.model.fields, first_column) && Models.is_many_to_many_field(instruct.object.model.fields[first_column])
    relation = Models.get_many_to_many_relation(instruct.object.model, first_column)
    tb_alias, row_join, foreign_model, last_field = _apply_many_to_many_branch(
      relation, instruct, Models.model_table_name(instruct.object.model), instruct.alias,
      join_path, vector; track_path = !cte
    )
    foreign_table_name = foreign_model
    inserted = true
  elseif first_column in instruct.object.model.field_names || _get_join_field(instruct.object, join_path) !== nothing
    # A `cjoin(field = …)` entry on this path supplies the link field itself; the first hop is the
    # only one that can carry such an override, which is why the choice stays here.
    first_field = _get_join_field(instruct.object, join_path) !== nothing ? _get_join_field(instruct.object, join_path) : instruct.object.model.fields[first_column]
    row_join, foreign_table_name, last_field = _forward_fk_hop(
      instruct, instruct.object.model, Models.model_table_name(instruct.object.model), instruct.alias,
      first_column, first_field, vector; prev_how = nothing,
      no_target_message = "Invalid field path: the column $(first_column) does not have a foreign key")
  elseif haskey(instruct.object.model.related_objects, vector[1])
    related_object = instruct.object.model.related_objects[vector[1]]
    if related_object isa Models.ManyToManyRelation
      relation = related_object::Models.ManyToManyRelation
      tb_alias, row_join, foreign_model, last_field = _apply_many_to_many_branch(
        relation, instruct, Models.model_table_name(instruct.object.model), instruct.alias,
        join_path, vector; reverse=true, track_path = !cte
      )
      foreign_table_name = foreign_model
      inserted = true
    else
      rel = related_object::Models.ReverseRelation
      length(vector) == 1 && throw(QueryBuildError("Invalid field path: $(vector[1]) is a reverse field, you must inform the column to be selected. Example: ...filter(\"$(vector[1])__column\")"))
      # Unlike the loop's reverse arm, the first hop does NOT check `vector[2]` against the child's
      # field names here — an unknown terminal column falls through to `_solve_field`'s typed error
      # (#446). Long-standing; #68 keeps each hop reporting what it reported.
      row_join, foreign_table_name, last_field = _reverse_hop(
        instruct, instruct.object.model, Models.model_table_name(instruct.object.model), instruct.alias,
        rel, vector; prev_how = nothing)
    end
  else
    @pormg_debug false
    # #492: a CTE-rooted string reaches this branch only when the resolution pass did not walk it.
    # The gate does NOT live here, deliberately — `_resolve_cte_string_paths!` (`ctes.jl`) owns it,
    # because a decision made here has only a `Vector{String}` to work with and cannot retag the
    # caller's `SQLField`; leaving `root` at `:base` while the join builder keys `:cte` is a silent
    # memo miss that costs the sargable date rewrite and the JSON branch. Do not "simplify" the gate
    # back into this cascade. See the pass's own header for the four failure modes.
    #
    # What survives here is the SCOPE message. A `__` path names a CTE column wherever a column path
    # is accepted — `values()`, `filter()` keys, `order_by()`, function arguments — but `F(...)` is
    # not one of those: `FExpression`'s slots do not admit `SQLTypeCTE`, a widening #444 declined and
    # #492 did not revisit. Without this the reader gets "column not found" and goes looking for a
    # model field that was never the point.
    if haskey(instruct.object.ctes, vector[1])
      rest = length(vector) > 1 ? join(vector[2:end], "__") : "column"
      throw(UnknownFieldError(
        "\e[4m\e[31m$(join(vector, "__"))\e[0m is not a field path on " *
        "\e[4m\e[32m$(instruct.object.model.name)\e[0m, and \e[4m\e[31m$(vector[1])\e[0m is a CTE " *
        "declared on this query.\n  A \e[4m\e[32m__\e[0m path reaches a CTE column in " *
        "\e[4m\e[32mvalues(...)\e[0m, \e[4m\e[32mfilter(...)\e[0m keys, " *
        "\e[4m\e[32morder_by(...)\e[0m and function arguments — but not here.\n  " *
        "Write \e[4m\e[32mCTE(\"$(vector[1])\", \"$(rest)\")\e[0m instead (#492)."))
    end
    # #446: through the shared funnel. This site built the same sentence by hand with UNSORTED field
    # names and a slightly different tail, so a user saw one format when they typo'd the first path
    # segment and another when they typo'd a later one — for the same mistake.
    throw(_unknown_field(instruct.object.model, vector[1]))
  end

  # #447: skipping the config lookups for a CTE hop (inside `_finish_hop!`) is what stopped a
  # `cjoin` / `on()` entry that happened to share the CTE's name from handing the CTE's join its
  # type and predicates, and `track_path = !cte` is what stopped `_insert_join` claiming the CTE
  # name in `row_path` — the three symptoms of that issue, all unrepresentable now.
  inserted || ((tb_alias, row_join) = _finish_hop!(instruct, row_join, join_path; cte = cte))
  
  vector = vector[2:end]  

  @pormg_debug false
  
  while size(vector, 1) > 1
    # get new object
    @pormg_debug false
    join_path = join(field[1:length(field)-length(vector) + 1], "__")
    new_object = foreign_table_name::PormGModel
    first_column = _resolve_fk_short_form(new_object, vector[1])

    # #27: a non-terminal JSON field reached through FK joins (e.g. `fk__payload__key`) is a value
    # extraction on the joined table's alias, not a further hop. size(vector) > 1 here, so the
    # trailing segments are a JSON path.
    if haskey(new_object.fields, first_column) && Models.is_json_field(new_object.fields[first_column])
      return _render_json_lookup(instruct, tb_alias, new_object.fields[first_column], first_column, String.(vector[2:end]), field; cte=cte)
    end

    # Read the hop we came from before the arms below construct the next row (#487: a fresh
    # `JoinRow` per hop, so nothing previously inserted is ever edited).
    prev_how = _prev_how(row_join)
    prev_b = row_join.b

    inserted = false

    if haskey(new_object.fields, first_column) && Models.is_many_to_many_field(new_object.fields[first_column])
      relation = Models.get_many_to_many_relation(new_object, first_column)
      tb_alias, row_join, foreign_model, last_field = _apply_many_to_many_branch(
        relation, instruct, prev_b, tb_alias, join_path, vector; previus_how=prev_how, track_path = !cte
      )
      foreign_table_name = foreign_model
      inserted = true
    elseif first_column in new_object.field_names
      first_field = new_object.fields[first_column]
      # This guard fires BEFORE the join type is derived — so a non-FK column here never reaches
      # `_determine_join_type`'s operator hint, unlike at the first hop. Kept in the caller for
      # exactly that reason: the helper must not decide the order (#68).
      !hasfield(typeof(first_field), :to) && throw(QueryBuildError("Invalid field path: the column $(first_column) is a field from $(new_object.name), but it does not have a foreign key"))
      row_join, foreign_table_name, last_field = _forward_fk_hop(
        instruct, new_object, prev_b, tb_alias, first_column, first_field, vector; prev_how = prev_how,
        # #197: this used to blame `vector[2]`, but the FK-less column is `first_column`.
        no_target_message = "Invalid field path: the column $(first_column) in $(new_object.name) does not have a foreign key target")
    elseif haskey(new_object.related_objects, vector[1])
      related_object = new_object.related_objects[vector[1]]
      if related_object isa Models.ManyToManyRelation
        relation = related_object::Models.ManyToManyRelation
        tb_alias, row_join, foreign_model, last_field = _apply_many_to_many_branch(
          relation, instruct, prev_b, tb_alias, join_path, vector; previus_how=prev_how, reverse=true, track_path = !cte
        )
        foreign_table_name = foreign_model
        inserted = true
      else
        rel = related_object::Models.ReverseRelation
        length(vector) == 1 && throw(QueryBuildError("Invalid field path: $(vector[1]) is a reverse field, you must inform the column to be selected. Example: ...filter(\"$(vector[1])__column\")"))
        # Loop-only check (the first hop lacks it — see there); stays in the caller so the helper
        # does not silently give the first hop a message it never had.
        !(vector[2] in rel.model_resolved.field_names) && throw(UnknownFieldError("Invalid field path: the column $(vector[2]) not found in $(rel.model_resolved.name)"))
        row_join, foreign_table_name, last_field = _reverse_hop(
          instruct, new_object, prev_b, tb_alias, rel, vector; prev_how = prev_how)
      end

    else
      throw(UnknownFieldError("Invalid field path: the column $(vector[1]) not found in $(new_object.name)"))
    end

    @pormg_debug false   
    inserted || ((tb_alias, row_join) = _finish_hop!(instruct, row_join, join_path; cte = cte))

    # Every arm consumes exactly ONE segment per iteration. The reverse arm used to advance in-arm
    # and set a `_reverse_advanced` flag that made this line skip — a no-op pair, since the two
    # advances were never both taken (#68).
    vector = vector[2:end]
  end

  # tb_alias is the last table alias in the join ex. tb_1
  # last_column is the last column in the join ex. last_login
  # vector is the full path to the column ex. user__last_login__date (including functions (except the suffix))

  # @pormg_debug

  # println("$(join(field, "__"))")
  # functions must be processed here
  # `memo_field!` is typed on `PormGField` (#474/#478), so a `nothing` here would raise a MethodError
  # BEFORE `_solve_field` below could report the real problem — which is the whole point of letting
  # the lookups above fall through. Guarding the write is what makes that fall-through reach the
  # typed error. Nothing depends on the entry existing: every reader tolerates a miss.
  # #474: namespaced for a CTE-rooted path — same argument as `row_path` and `instruct.cache`.
  last_field !== nothing && memo_field!(instruct, memo_key(cte ? :cte : :base, join(field, "__")), last_field)
  return string(quote_identifier(tb_alias, instruct.connection), ".", _solve_field(vector[end], foreing_table_module, foreign_table_name, instruct))
  
end