
"build a row to join"
function _determine_join_type(field::PormGField; previus_how::Union{String, Nothing} = nothing, second_fild_name::Union{String, Nothing}=nothing)
  if previus_how !== nothing && previus_how == "LEFT"
    # if the previous join was a LEFT JOIN, the current join must be a LEFT JOIN
    return "LEFT"
  end
  
  @pormg_debug false
  if !hasproperty(field, :how)
    if second_fild_name !== nothing
      _check_if_field_is_a_operator(second_fild_name)
    end
    throw(QueryBuildError("The field '$(field)' does not have a 'how' property"))
  elseif field.how !== nothing && !isempty(field.how)
    return _normalize_join_type(field.how)
  end
  
  return field.null ? "LEFT" : "INNER"
end

"""
    _cache_join(field::String, instruct::SQLInstruction)

Checks if a join path `field` is already in the cache. If not, and it's a join path (contains `__`), 
it attempts to build the join and cache it. Returns `true` if the field is in cache 
(either before or after the attempt), `false` otherwise.
"""
function _cache_join(field::String, instruct::SQLInstruction)
  haskey(instruct.cache, (false, field)) && return true
  
  if contains(field, "__")
    try
      # Build the join and get the SQL selector (e.g., "Tb.column")
      sql_selector = _build_row_join(split(field, "__") |> Vector{String}, instruct)
      
      # Populate the cache so it can be used immediately
      instruct.cache[(false, field)] = SQLField(sql_selector, field)   # #474: base-model namespace
      return true
    catch e
      return false
    end
  end
  return false
end

# #45 — materialize a `cjoin_on` entry into a row_join WITHOUT the FK-driven anchor path. The ON
# clause is entirely user-provided (config["filters"]); no `main.key_a = joined.key_b` equi-anchor
# is emitted (build_row_join_sql_text skips it when "no_anchor" == "1"). key_a/key_b are never
# rendered for an anchor-less entry, but `_insert_join`'s dedup keys on (a, b, key_a, key_b, alias_a)
# and NOT alias_b — so we set key_a to the unique user alias, otherwise two cjoin_on joins to the
# same target model would collide and one would be silently dropped.
function _build_cjoin_on_row_join(config::Dict{String,Any}, join_path::String, instruct::SQLInstruction)::Nothing
  target_model = getfield(instruct.object.model._module, Symbol(config["target_model"]::String))::PormGModel
  user_alias = config["user_alias"]::String
  row_join = Dict{String,Union{String,Vector{FilterType}}}(
    "a"         => Models.model_table_name(instruct.object.model),
    "alias_a"   => instruct.alias,
    "b"         => Models.model_table_name(target_model),
    "alias_b"   => user_alias,
    "key_a"     => user_alias,   # dedup discriminator (never rendered for no_anchor)
    "key_b"     => "",
    "how"       => (get(config, "join_type", "INNER"))::String,
    "no_anchor" => "1",
  )
  filters = get(config, "filters", nothing)
  if filters isa Vector{FilterType} && !isempty(filters)
    row_join["on_conditions"] = filters
  end
  # #480 — fail closed on a range variable the statement already has. `_get_alias_name` now steps
  # around every declared `cjoin_on` alias, so a GENERATED alias can no longer take this one; what
  # is left is the base relation's own alias (`instruct.alias`, never generated by that function)
  # and any producer that bypassed it. Both would render two `AS "<alias>"` in one FROM list —
  # invalid SQL, or an ON clause and a projection that silently name different relations.
  holder = user_alias == instruct.alias ? row_join["a"]::String : nothing
  if holder === nothing
    for r in instruct.row_join
      if r["alias_a"] == user_alias || r["alias_b"] == user_alias
        holder = r["b"]::String
        break
      end
    end
  end
  if holder !== nothing
    throw(QueryBuildError(
      "cjoin_on alias \"$(user_alias)\" is already the alias of \"$(holder)\" in this statement; " *
      "two range variables cannot share a name. Choose another alias."))
  end
  _insert_join(instruct.row_join, row_join, instruct.row_path, join_path)
  return nothing
end

function _build_row_join(field::Vector{SubString{String}}, instruct::SQLInstruction; as::Bool=true, cte::Bool=false)
  # convert the field to a vector of string
  vector = String.(field)
  _build_row_join(vector, instruct, as=as, cte=cte)
end

# Resolve one join-path segment to the field that actually carries the relation, so a Django-style
# `driver__forename` reaches the FK column `driver_id`.
#
# #345 removed the `instruct.django === nothing && return field_name` gate that used to sit on top.
# It made this conditional on `Settings.django_prefix`, a **table-naming** option — the same "a naming
# flag silently switches behaviour on" shape #344 removed from sequence syncing, and worse here,
# because #345 is precisely the change that stops anyone needing the prefix for naming. Unsetting it
# turned working Django-style join paths into `UnknownFieldError`s, with nothing in the message
# pointing at the setting.
#
# The prefix was never needed for this to be correct: the `_id` convention lives on the MODEL, which
# is what the lookups below read. Ungating is additive for a prefix-less connection — every branch
# below is reached only when the segment resolves to nothing on its own, so a path that worked before
# still resolves the same way and one that used to throw a few frames later now joins. It is NOT
# universally additive: see the `related_objects` guard below, which is where the one behaviour change
# for PREFIXED connections is described.
#
# #345 also DELETED the rejection of the explicit `driver_id__forename` spelling that lived here.
# That was a style rule, not a correctness one — both spellings render identical SQL — and it was
# only ever enforced for prefixed connections. Making it universal broke `cjoin`, whose key must be
# in `model.field_names` and is therefore necessarily the `_id` column (`ctes.jl`), and
# `PormGRow.save()`, which splits a projected key on `__` and looks the prefix up verbatim in
# `model.fields` — so the short form it recommended raises `KeyError` on the write path. PormG's own
# `test/integration/test_row_mutation.jl` uses the explicit spelling. There is no spelling that
# satisfies both paths, which is the tell that the rule was wrong rather than the call sites.
#
# `instruct` went with the gate — it was the only thing this function read it for.
function _resolve_fk_short_form(model::PormGModel, field_name::String)::String
  # The field exists directly — including the explicit `<fk>_id` form, which resolves to itself.
  # Single O(1) dict lookup replaces the previous O(n) vector scan + dict access.
  haskey(model.fields, field_name) && return field_name

  # An EXPLICIT relation claims the name, so the implicit rewrite defers to it (#345).
  #
  # `_build_row_join` tries the forward-FK branch on the RESOLVED column and the reverse branch on
  # the RAW segment, in that order. So rewriting `x` to `x_id` here when `x` is also a reverse
  # accessor moves the path from one branch to the other: a different table, joined on a different
  # column, with no error. Take a model with FK `circuit_id` and a child declaring
  # `related_name = "circuit"` — `circuit__name` means the child, in reverse.
  #
  # This is a genuine ambiguity that PormG has to resolve one way, and it resolved it BOTH ways
  # before #345, depending on a table-naming option: prefix-less connections read the reverse
  # relation (the gate returned early), prefixed ones read the forward FK (resolution ran). The rule
  # is now the same for everyone, and it is the one that keeps an author's explicit declaration
  # authoritative: `related_name = "circuit"` is a name someone chose, while `circuit` -> `circuit_id`
  # is a convenience this function invents. An invented name must not displace a declared one.
  #
  # Do NOT reach for Django's `fields.E302` to argue the clash is already ill-formed — it is not, for
  # PormG. E302 compares a reverse accessor against the target's FIELD names, and a Django FK spelled
  # `driver` IS the field `driver`, so it collides. A PormG-native model declares that FK as
  # `driver_id`, which `driver` does not collide with, so the model set is perfectly legal here.
  # `test/unit/test_complex_queries.jl`'s `FkShortFormModels` is exactly such a set.
  haskey(model.related_objects, field_name) && return field_name

  # Short-form resolution: "driver" → "driver_id" when a FK with that name exists.
  # This only applies to snake_case FK convention (e.g. driver_id).
  # camelCase FKs (e.g. driverid) must be referenced by their full field name.
  fk_field = get(model.fields, field_name * "_id", nothing)
  if fk_field !== nothing && hasfield(typeof(fk_field), :to)
    return field_name * "_id"
  end

  return field_name
end

# Resolve one side of an M2M relation (owner or related) to its PormGModel within `_module`:
# by binding first, then by formatted model name. Lets the join builder read each side's
# `db_column` for its PK (#64) — the relation stores only string names/bindings.
function _resolve_m2m_side_model(_module::Module, binding::String, model_name::String, field_name::String)::PormGModel
  bsym = Symbol(binding)
  if isdefined(_module, bsym)
    candidate = Base.invokelatest(getfield, _module, bsym)
    candidate isa PormGModel && return candidate
  end

  target_name = Models.format_model_name(model_name)
  for model in Models.get_all_models(_module)
    Models.format_model_name(model.name) == target_name && return model
  end

  throw(QueryBuildError("The many-to-many model $(binding) for accessor $(field_name) is not defined"))
end

function _resolve_many_to_many_related_model(_module::Module, relation::Models.ManyToManyRelation)::PormGModel
  return _resolve_m2m_side_model(_module, relation.related_binding, relation.related_model, relation.field_name)
end

function _insert_many_to_many_joins(
  relation::Models.ManyToManyRelation,
  instruct::SQLInstruction,
  parent_table::String,
  parent_alias::String,
  join_path::String;
  previus_how::Union{String, Nothing}=nothing,
  track_path::Bool=true,
)
  join_type = previus_how == "LEFT" ? "LEFT" : "INNER"

  # #64: the PARENT-side join keys (owner_pk / related_pk) are field NAMES; resolve each to
  # its physical column via the owning model's db_column. `model_column` is a strict no-op when the
  # PK has no db_column.
  #
  # The through-table columns (owner_column / related_column) go in as-is, and since #377 that is a
  # claim about the SLOT, not a bet about the model. Both are resolved to physical columns once, at
  # registration, exactly as `through_table` is one line below: on the AUTO path they are names PormG
  # generated for a table PormG created, and on an explicit `through=` they are
  # `Models.model_column(through_model, <the FK field name>)`.
  #
  # Before that they were the through model's FIELD NAME, rendered raw — equal to the physical column
  # exactly when the field declared no `db_column`. Django's default convention satisfies that
  # (`driver` imports as the field `driver_id`, which is also Django's column), which is why an
  # ordinary import joined correctly and the bug survived; a `db_column=` written in the Django source
  # did not, because the importer splats it onto the field it builds (`process_class_fields!`). The
  # shape was origin-independent — hand-written models reached it the same way.
  _module = instruct.object.model._module::Module
  owner_model = _resolve_m2m_side_model(_module, relation.owner_binding, relation.owner_model, relation.field_name)
  related_model = _resolve_m2m_side_model(_module, relation.related_binding, relation.related_model, relation.field_name)

  through_row = sizehint!(Dict{String, Union{String, Vector{FilterType}}}(), 8)
  through_row["a"] = parent_table
  through_row["alias_a"] = parent_alias
  through_row["key_a"] = Models.model_column(owner_model, relation.owner_pk)
  # #363: the through side's PHYSICAL table. This slot carried the through model's LOGICAL name
  # whenever the relation came from an explicit `through=`, so a through model with a `db_table`
  # joined against a table that does not exist. `through_table` is resolved once, at registration.
  through_row["b"] = relation.through_table
  through_row["alias_b"] = _get_alias_name(instruct)
  through_row["key_b"] = relation.owner_column
  through_row["how"] = join_type

  through_alias = _insert_join(instruct.row_join, through_row, instruct.row_path, "$(join_path)__through"; track_path=track_path)

  related_row = sizehint!(Dict{String, Union{String, Vector{FilterType}}}(), 8)
  related_row["a"] = relation.through_table
  related_row["alias_a"] = through_alias
  related_row["key_a"] = relation.related_column
  # The related side's PHYSICAL table (db_table when set, #59). Unlike `through_table` above,
  # `relation.related_model` carries the LOGICAL name — that is what identifies the model — so this
  # slot, which is rendered as a table, has to go through `model_table_name`.
  related_row["b"] = Models.model_table_name(related_model)
  related_row["alias_b"] = _get_alias_name(instruct)
  related_row["key_b"] = Models.model_column(related_model, relation.related_pk)
  related_row["how"] = join_type

  return _insert_join(instruct.row_join, related_row, instruct.row_path, join_path; track_path=track_path)
end

function _row_join_for_alias(row_join::Vector{Dict{String, Union{String, Vector{FilterType}}}}, alias::String)
  for row in row_join
    row["alias_b"] == alias && return row
  end
  error(_emsg("PormG internal error: join alias $(alias) was not found in row_join — this should not happen; please report it."))
end

# Physical table for a REVERSE join target (#59). The reverse path reaches its target through
# `related_objects`, which stores the model's LOGICAL name — so the resolved model is the only place
# a `db_table` can be read from, and it must win. Without an override this reproduces the previous
# derivation byte for byte, including the `django_prefix` arm.
#
# That arm used to be the ONLY way a prefixed deployment's table got spelled, because no generated
# model declared one. Since #345 the Django importer pins `db_table` on every model it emits, so a
# regenerated file takes the early return and the arm is dead for it. It stays for the files that
# have not been regenerated, and for a hand-written model on a prefixed connection.
function _reverse_join_table(reverse_model::PormGModel, logical_name::AbstractString, django)::String
  Models.model_has_db_table(reverse_model) && return Models.model_table_name(reverse_model)
  return django !== nothing ? string(django, lowercase(logical_name)) : lowercase(logical_name)
end

# FORWARD FK/O2O join target whose `.to` is still a STRING (#388). `.to` names the target's Julia
# BINDING (#360/#386), never its table, so the only correct move is to resolve the binding in the
# owning models module and read the table off the model — which is exactly what the resolved-`.to`
# arm beside each call site already does, and what the next-hop lookup does one line later.
#
# Both call sites used to `lowercase` the binding into a table name instead. That inverts
# `uppercasefirst`, which is the right inverse only while the binding IS `uppercasefirst(<table>)`:
# a table `2fast` binds as `Col_2fast` and joined `col_2fast`, `driver profile` binds as
# `Driver_profile` and joined `driver_profile`. Neither table exists. It also ignored `db_table`
# outright, so a parent pinned to an explicit table joined the wrong one even when the guess would
# otherwise have inverted cleanly.
#
# The `instruct.django` arm went with it, deliberately. That prefix fallback is documented as the
# spelling for a REVERSE-join target carrying no `db_table` (`docs/src/schema_conventions.md` →
# *`django_prefix` interop*), and the resolved-model arm this now joins has never applied it — so the
# arm only fired when a key happened to reach the String branch, which rendered ONE foreign key as
# two different tables depending on whether `set_models` had resolved its target yet.
#
# Raises rather than returning `nothing`: an unresolvable binding cannot produce a join at all. What
# changes here is the ERROR, not whether there is one — the old code always failed too, just as a
# bare `UndefVarError` from a `getfield`: at this hop when the path had exactly two segments, and
# one iteration later in the `while` loop (`new_object = getfield(…)`) when it had more. Both name a
# Julia symbol rather than the field path the user wrote, which is the part worth fixing.
#
# The genuinely SILENT case was never the unresolvable binding — it was a binding that DOES resolve
# but whose table is not `lowercase(binding)`, which produced a perfectly well-formed `JOIN` against
# the wrong table. Not necessarily a MISSING one: `Driver_Profile` folds to `driver_profile`, which on
# PostgreSQL is a second, real table that may exist and hold someone else's rows — a query that
# returns results, all of them wrong. That is the case the two mixed-case join testsets pin.
function _forward_join_model(to::AbstractString, mod::Module, owner::PormGModel, column::AbstractString)::PormGModel
  model = Models._resolve_target_model(to, mod)
  model isa PormGModel && return model
  throw(QueryBuildError(
    "Invalid field path: the foreign key \e[31m$(column)\e[0m in \e[32m$(owner.name)\e[0m targets " *
    "\e[31m$(to)\e[0m, which is not a model binding in \e[32m$(mod)\e[0m. A ForeignKey `to` string " *
    "names a Julia model binding, not a table, so there is no table to join."))
end

# Shared helper used at the four sites in `_build_row_join` where a many-to-many
# (forward or reverse) hop must be expanded into the through-table + related-table
# join pair. Returns the alias of the related-table join, the row dict for that
# join, the resolved related PormGModel, and (when applicable) the trailing
# `last_field` reference.
function _apply_many_to_many_branch(
  relation::Models.ManyToManyRelation,
  instruct::SQLInstruction,
  parent_table::String,
  parent_alias::String,
  join_path::String,
  vector::Vector{String};
  previus_how::Union{String, Nothing}=nothing,
  reverse::Bool=false,
  track_path::Bool=true,
)
  foreing_table_module = instruct.object.model._module::Module
  foreign_model = _resolve_many_to_many_related_model(foreing_table_module, relation)
  if length(vector) == 1
    msg = reverse ? "many-to-many reverse field" : "many-to-many field"
    throw(QueryBuildError("Invalid field path: $(vector[1]) is a $(msg), you must inform the column to be selected. Example: ...filter(\"$(vector[1])__column\")"))
  end
  # `get(..., nothing)` rather than a raw index (#446). An unknown terminal column used to die here
  # with a bare `KeyError` naming an internal dict lookup. Falling through leaves `last_field`
  # unset and lets `_solve_field` at the end of this function raise the typed `UnknownFieldError`
  # that names the column, the model and its available fields — one message for every hop shape
  # instead of a KeyError here and a good error three lines later.
  last_field = size(vector, 1) == 2 ? get(foreign_model.fields, vector[2], nothing) : nothing
  tb_alias = _insert_many_to_many_joins(relation, instruct, parent_table, parent_alias, join_path, previus_how=previus_how, track_path=track_path)
  row_join = _row_join_for_alias(instruct.row_join, tb_alias)
  # #74: the related table reached through a many-to-many is the "many-side". Flag the (deduped)
  # row_join entry so the fan-out guard can refuse silently-inflated aggregates over base columns.
  row_join["to_many"] = "1"
  return (tb_alias, row_join, foreign_model, last_field)
end

# #27: validate JSON path key segments fail-closed. A segment is either a non-negative integer
# (JSON array index) or a safe key (`SAFE_JSON_KEY_PATTERN`). Anything else (spaces, dots, quotes,
# braces, empty) is rejected, so the validated segments are safe to interpolate into the path
# literal. Returns the segments unchanged.
#
# #394: this checks `SAFE_JSON_KEY_PATTERN`, NOT `SAFE_IDENTIFIER_PATTERN`, even though the two
# bodies match today. A segment is interpolated UNQUOTED into a path literal inside a single-quoted
# SQL string (PostgreSQL braces, SQLite `$.a.b`), so unlike a table or column name it has no quoting
# to fall back on and this charset check is the entire guard. Keeping the constants separate is what
# stops a future relaxation of the SQL-identifier rules from silently widening this one.
function _validate_json_key_segments(segments::Vector{String})::Vector{String}
  for seg in segments
    if occursin(r"^\d+$", seg) || occursin(SAFE_JSON_KEY_PATTERN, seg)
      continue
    end
    throw(InvalidValueError("Invalid JSON key segment \e[31m$(seg)\e[0m in a JSON path lookup. Segments must be a non-negative integer (array index) or a simple key (letters, digits, underscore). Keys with spaces, dots, or quotes are not addressable via the `__` path syntax."))
  end
  return segments
end

# #27: render a JSON path lookup (e.g. `payload__driver`, `payload__0__name`) as a TEXT extraction
# on the resolved column. The base field is a non-terminal JSONField, so the trailing segments are
# a value path, not join hops. Records the resolved path in json_lookup_cache (so the filter-render
# branch binds the RHS as plain text) and tab_field_cache (so downstream sees the base field type).
function _render_json_lookup(instruct::SQLInstruction, alias::String, json_field::PormGField,
    field_name::String, key_segments::Vector{String}, full_field::Vector{String};
    cte::Bool=false)::String
  segs = _validate_json_key_segments(key_segments)
  col = string(quote_identifier(alias, instruct.connection), ".",
               safe_column_identifier(Models.field_db_column(json_field, field_name), instruct.connection))
  # #474: both caches below are keyed by the resolved path, so a CTE-rooted lookup namespaces it for
  # the same reason `row_path` does — `CTE("ev", "meta__driver")` and a model path `ev__meta__driver`
  # produce the same string and must not share an entry.
  path = _join_path_key(join(full_field, "__"), cte)
  instruct.json_lookup_cache[path] = (json_field, segs)
  instruct.tab_field_cache[path] = json_field
  return Dialect._json_extract_expr(instruct.connection, col, segs)
end

function _build_row_join(field::Vector{String}, instruct::SQLInstruction; as::Bool=true, cte::Bool=false)
  vector = copy(field)
  # The `String` member is UNREACHABLE as of #388, and deliberately left in place. Every one of the
  # nine assignments below now stores a resolved model — `cte_model`, `_apply_many_to_many_branch`'s
  # `foreign_model` (×4), `first_model`/`next_model` (the forward arms), and `reverse_model` (×2) —
  # so narrowing this to `Union{PormGModel, Nothing}` would make that invariant enforced rather than
  # merely true. It is not narrowed here because the annotation would then `convert` on assignment,
  # turning any path this audit missed from a working query into a `TypeError`. The unit suite does
  # reach these branches (`test_cte_ergonomics.jl`, `test_many_to_many.jl`), but not all four M2M call
  # sites, and this change is not authorized to run the integration suite that would. Narrow it in a
  # change that can; until then the `isa PormGModel` tests downstream stay.
  foreign_table_name::Union{String, PormGModel, Nothing} = nothing
  foreing_table_module::Module = instruct.object.model._module::Module
  row_join = sizehint!(Dict{String, Union{String, Vector{FilterType}}}(), 8)
 
  @pormg_debug false

  first_column = _resolve_fk_short_form(instruct.object.model, vector[1])
  last_field::Union{Nothing, PormGField} = nothing
  join_path = field[1]
  m2m_inserted = false

  # #27: a non-terminal JSON base field is a value extraction (`payload__key`, `payload__0__name`),
  # not a join hop. Fire before the CTE/FK cascade — otherwise `payload` enters the forward-FK
  # branch and crashes in `_determine_join_type` (a JSONField has no `.how`). A TERMINAL JSON field
  # (length == 1) is left to resolve as a plain jsonb column (the target of the containment operators).
  #
  # `!cte` because a CTE-scoped path is resolved against the CTE's own model, not the base model. A
  # CTE named after a base-model JSONField would otherwise be extracted from that field's jsonb.
  if !cte && haskey(instruct.object.model.fields, first_column) &&
     Models.is_json_field(instruct.object.model.fields[first_column]) &&
     length(vector) > 1
    return _render_json_lookup(instruct, instruct.alias,
      instruct.object.model.fields[first_column], first_column, String.(vector[2:end]), field)
  end

  # #444: a CTE is reached ONLY through `CTE(name, path)`, which sets `cte=true`. It is no longer
  # discovered by testing `haskey(instruct.object.ctes, vector[1])` on a plain field path.
  #
  # That test WAS this branch's condition, and it sat ahead of the many-to-many, forward-FK and
  # reverse-relation arms below — so for any first segment naming both a CTE and something on the
  # model, the CTE won and the model's own join was never emitted. Silently: the only signal was the
  # #44 Cartesian warning, which reports an uncorrelated CROSS JOIN rather than a shadowed relation
  # (#431). Splitting the namespaces removes the precedence question entirely rather than answering
  # it — `.with("parent" => …)` and the `parent` ForeignKey now coexist in one query, each
  # addressable, neither shadowing the other.
  if cte
    @pormg_debug false
    cte_name = vector[1]
    # #444: the single point where a `CTE(name, …)` handle is checked against the query's registry.
    # Both render entries (`_get_select_query` / `_get_filter_query`) funnel through here, so neither
    # has to repeat it.
    if !haskey(instruct.object.ctes, cte_name)
      declared = isempty(instruct.object.ctes) ? "none" : join(sort(collect(keys(instruct.object.ctes))), ", ")
      throw(UnknownFieldError(
        "CTE \e[4m\e[31m$(cte_name)\e[0m is not declared on this query; declared CTEs: " *
        "\e[4m\e[32m$(declared)\e[0m. Add it with \e[4m\e[32m.with(\"$(cte_name)\" => subquery)\e[0m."))
    end
    cte_dict = instruct.object.ctes[cte_name]
    # #433: this is NOT an internal invariant, which is what it claimed to be until the #433 audit.
    # `cte_dict["model"]` is written in exactly one place — `_build_cte_custom_model`, reached only
    # from `build_cte_clause`. So a missing "model" means precisely one thing: THIS statement never
    # ran `build_cte_clause`, and therefore emits no `WITH` clause at all. Referencing the CTE would
    # name a relation the statement never declares. That is a property of the statement kind, not a
    # broken invariant, and it is reachable from ordinary user input:
    #
    #     q.with("gv" => sub, join_field = "parent" => "id")
    #     q.filter("gv__code" => "X")
    #     q.update("note" => "n")        # update() never calls build_cte_clause
    #
    # `update()`'s own CTE refusal (#394, `_get_join_condition_list`) cannot catch that, because it
    # inspects `row_join` entries — which this function is in the middle of producing.
    #
    # Guarding HERE rather than at each caller is deliberate. `build()` has SIX call sites and only
    # three render a `WITH`: `execution.jl` `query`/`_count`/`_exists` do; `_update`,
    # `bulk_update` (`execution_bulk.jl`) and `_build_exists_query` (`build_helpers.jl`, which
    # hand-rolls its own SELECT) do not. A per-caller guard would have to be re-added for each
    # future one. This is the single point where the missing render step becomes observable.
    #
    # The message deliberately does NOT name `update()` as the only culprit: `_build_exists_query`
    # is a READ-path renderer that also emits no `WITH`, so "reads render a CTE" would be a lie on
    # that route. It is currently unreachable only because `_guard_no_nested_cte` refuses a nested
    # CTE earlier with a better message — a single-point dependency worth not encoding into text.
    if !haskey(cte_dict, "model")
      throw(QueryBuildError(
        "The CTE \e[4m\e[31m$(cte_name)\e[0m is referenced here, but the statement being built " *
        "emits no \e[4m\e[32mWITH\e[0m clause — so the CTE would never be declared.\n  " *
        "\e[4m\e[32mlist\e[0m / \e[4m\e[32mfirst\e[0m / \e[4m\e[32mcount\e[0m / " *
        "\e[4m\e[32mexists\e[0m render a CTE. \e[4m\e[32mupdate(...)\e[0m and " *
        "\e[4m\e[32mbulk_update(...)\e[0m do not.\n  " *
        "Scope the statement with a plain \e[4m\e[32m.filter(...)\e[0m or a subquery instead of a " *
        "CTE (#433)."))
    end
    cte_model = cte_dict["model"]::PormGModel
    
    # #444: unreachable from user input — `CTE(name, path)` refuses an empty path at construction,
    # with a message that names the call the user wrote. Kept as a fail-closed backstop so a future
    # internal caller passing a one-element vector gets this instead of a KeyError on `vector[2]`.
    length(vector) == 1 && throw(QueryBuildError("CTE reference '$(cte_name)' must include a column path. Example: CTE(\"$(cte_name)\", \"field_name\")"))

    # Get the join field configuration from the CTE
    jf = cte_dict["join_field"]

    if jf === nothing
      # #44: no join_field → the CTE is CROSS JOINed and the correlation is supplied by the
      # main query's `F("<cte>__col")` filter(s), which render verbatim in WHERE. `join_type`
      # does not apply to a CROSS JOIN (INNER-like by nature).
      if !haskey(cte_model.fields, vector[2])
        available = join(collect(keys(cte_model.fields)), ", ")
        throw(UnknownFieldError("CTE field '$(vector[2])' not found in '$(cte_name)'; available fields: $(available)"))
      end
      row_join["a"] = Models.model_table_name(instruct.object.model)
      row_join["alias_a"] = instruct.alias
      row_join["b"] = cte_name  # CTE name becomes the table name
      # #394: mark it. A correlated UPDATE ... FROM emits no `WITH` prefix, so a row_join naming a
      # CTE renders `FROM "<cte>" AS "Tb_N"` against a relation the statement never declares.
      # `_get_join_condition_list` refuses the whole class on this marker.
      row_join["cte"] = "1"
      row_join["alias_b"] = _get_alias_name(instruct)
      # "how" is never emitted for a CROSS entry (build_row_join_sql_text short-circuits on the
      # "cross" marker), but the deep-path loop below reads `row_join["how"]` as `prev_how`; set
      # it so an over-long path like `F("r91__col__more")` fails with the same "not a foreign key"
      # message as the keyed path instead of a cryptic KeyError.
      row_join["how"] = "CROSS"
      # Sentinel key columns: `_insert_join`'s dedup reads key_a/key_b directly (KeyError
      # otherwise), and the CROSS branch of `build_row_join_sql_text` skips them. Equal empty
      # strings also dedup repeat references to the same CTE (e.g. r91__raceid, r91__round)
      # onto a single CROSS JOIN.
      row_join["key_a"] = ""
      row_join["key_b"] = ""
      row_join["cross"] = "1"
    else
      join_field_pair = jf::Pair{String, String}
      main_table_key = join_field_pair.first    # e.g., "driverid" from main table
      cte_table_key = join_field_pair.second    # e.g., "driverid" from CTE
      @pormg_debug false

      if !haskey(cte_model.fields, cte_table_key)
        available = join(collect(keys(cte_model.fields)), ", ")
        throw(UnknownFieldError("CTE join_field column '$(cte_table_key)' not found in $(cte_name); available fields: $(available)"))
      end


      if (main_table_key in instruct.object.model.field_names)
        row_join["alias_a"] = instruct.alias
        # #64: resolve the main-model join field to its physical column (db_column).
        row_join["key_a"] = Models.model_column(instruct.object.model, main_table_key)
      elseif haskey(instruct.cache, (false, main_table_key)) || _cache_join(main_table_key, instruct)
        # #474: the MAIN model's join field, so the base-model half of the namespace — never the
        # CTE's, even though this branch sits inside the CTE arm.
        cache_item = instruct.cache[(false, main_table_key)]
        v_split = split(cache_item.field |> x -> replace(x,  '"' => ""), ".")
        row_join["alias_a"] = v_split[1] |> string
        row_join["key_a"] = v_split[2] |> string
      else
        throw(UnknownFieldError("Main table join_field column '$(main_table_key)' not found in $(instruct.object.model.name); available fields: $(join(instruct.object.model.field_names, ", "))"))
      end

      # Set up the join with the CTE
      row_join["a"] = Models.model_table_name(instruct.object.model)

      row_join["b"] = cte_name  # CTE name becomes the table name
      row_join["cte"] = "1"     # #394 — see the CROSS branch above
      row_join["alias_b"] = _get_alias_name(instruct)
      row_join["how"] = cte_dict["join_type"]::String

      # #64: the CTE side stays the FIELD NAME — a CTE is a derived table whose columns are
      # the values() projection ALIASES (`"pk_code" AS "code"`), so the join references the
      # alias "code", not the physical column. Only the main-table side (key_a above) is a
      # real physical column and is db_column-resolved.
      # #376 generalized this from the KEY to every CTE COLUMN, by stripping db_column from the CTE
      # model's fields at construction. So this literal is now also what `Models.model_column(
      # cte_model, cte_table_key)` would answer — kept literal because it needs no lookup.
      row_join["key_b"] = cte_table_key
    end

    @pormg_debug false

    foreign_table_name = cte_model
    last_field = get(cte_model.fields, vector[2], nothing)
   
  elseif haskey(instruct.object.model.fields, first_column) && Models.is_many_to_many_field(instruct.object.model.fields[first_column])
    relation = Models.get_many_to_many_relation(instruct.object.model, first_column)
    tb_alias, row_join, foreign_model, last_field = _apply_many_to_many_branch(
      relation, instruct, Models.model_table_name(instruct.object.model), instruct.alias,
      join_path, vector; track_path = !cte
    )
    foreign_table_name = foreign_model
    m2m_inserted = true
  elseif first_column in instruct.object.model.field_names || _get_join_field(instruct.object, join_path) !== nothing
    row_join["a"] = Models.model_table_name(instruct.object.model)
    row_join["alias_a"] = instruct.alias
    # @pormg_debug
    first_field = _get_join_field(instruct.object, join_path) !== nothing ? _get_join_field(instruct.object, join_path) : instruct.object.model.fields[first_column]
    # @pormg_debug
    row_join["how"] = _determine_join_type(first_field, second_fild_name= size(vector, 1) > 1 ? vector[2] : nothing)
    first_target = first_field.to
    first_target === nothing &&
      throw(QueryBuildError("Invalid field path: the column $(first_column) does not have a foreign key"))
    # #388: the two arms are ONE arm now. A String `.to` is the target's binding, so resolving it
    # yields the same model a `set_models`-resolved `.to` already holds, and the table comes off that
    # model either way. Carrying the model forward (matching the reverse branch below, #343) also
    # spares the next hop and `_solve_field` from repeating the binding lookup.
    first_model = first_target isa PormGModel ? first_target :
      _forward_join_model(first_target, foreing_table_module, instruct.object.model, first_column)
    row_join["b"] = Models.model_table_name(first_model)
    size(vector, 1) == 2 && (last_field = get(first_model.fields, vector[2], nothing))
    foreign_table_name = first_model
    # @pormg_debug
    row_join["alias_b"] = _get_alias_name(instruct)
    # Local FK column and referenced parent column both honor db_column (#50).
    row_join["key_b"] = Models.fk_target_column(first_field)
    row_join["key_a"] = Models.field_db_column(first_field, first_column)
  elseif haskey(instruct.object.model.related_objects, vector[1])
    related_object = instruct.object.model.related_objects[vector[1]]
    if related_object isa Models.ManyToManyRelation
      relation = related_object::Models.ManyToManyRelation
      tb_alias, row_join, foreign_model, last_field = _apply_many_to_many_branch(
        relation, instruct, Models.model_table_name(instruct.object.model), instruct.alias,
        join_path, vector; reverse=true, track_path = !cte
      )
      foreign_table_name = foreign_model
      m2m_inserted = true
    else
    # @pormg_debug false
    # #343: the child model is READ off the relation, never rebuilt from its name. The old
    # `Symbol(uppercasefirst(lowercased_name))` could only ever spell `Xxxxx`, so a binding with an
    # internal capital (Dim_CNES, CustomUser) raised UndefVarError instead of joining.
    rel = related_object::Models.ReverseRelation
    reverse_model = rel.model_resolved
    length(vector) == 1 && throw(QueryBuildError("Invalid field path: $(vector[1]) is a reverse field, you must inform the column to be selected. Example: ...filter(\"$(vector[1])__column\")"))
    # !(vector[2] in reverse_model.field_names) && throw("Error in _build_row_join, the column $(vector[2]) not found in $(reverse_model.name)")
    row_join["a"] = Models.model_table_name(instruct.object.model)
    row_join["alias_a"] = instruct.alias
    join_field = reverse_model.fields[String(rel.fk_field)]
    row_join["how"] = _determine_join_type(join_field, second_fild_name= vector[2])
    size(vector, 1) == 2 && (last_field = get(reverse_model.fields, vector[2], nothing))
    # The LOGICAL name goes straight into the table fallback, which is the only thing that ever
    # wanted it — before #343 it was assigned to `foreign_table_name` and then overwritten below.
    row_join["b"] = _reverse_join_table(reverse_model, String(rel.model_name), instruct.django)

    row_join["alias_b"] = _get_alias_name(instruct)
    # Reverse join: key_a is the parent's referenced column, key_b the child's FK
    # column; both honor db_column (resolved in their own model, no-op without it) (#50).
    row_join["key_a"] = Models.model_column(instruct.object.model, String(rel.target_pk))
    row_join["key_b"] = Models.model_column(reverse_model, String(rel.fk_field))
    # #74: a reverse foreign key (one-to-many) makes the child table the many-side.
    row_join["to_many"] = "1"
    # Carry the RESOLVED model forward, matching the CTE and M2M branches. `foreign_table_name` is
    # already declared `Union{String, PormGModel, Nothing}`, and both cross-branch readers accept a
    # model: the next-hop lookup branches on `isa PormGModel`, and the terminal column resolver
    # dispatches to `_solve_field(::String, ::Module, ::PormGModel, …)`. That terminal site was a
    # FIFTH broken reconstruction, reached only if the join above had not already thrown.
    foreign_table_name = reverse_model
    @pormg_debug false
    end
  else
    @pormg_debug false
    # #444 migration diagnostic. `"ev__sku"` used to resolve to the CTE `ev`; it now resolves as a
    # field path and lands here. This is a THROW, not a resolution — the string spelling is gone, not
    # aliased — but the generic "column not found" below would send the reader looking for a missing
    # model field rather than at the spelling that changed.
    if haskey(instruct.object.ctes, vector[1])
      rest = length(vector) > 1 ? join(vector[2:end], "__") : "column"
      throw(UnknownFieldError(
        "\e[4m\e[31m$(join(vector, "__"))\e[0m is not a field path on " *
        "\e[4m\e[32m$(instruct.object.model.name)\e[0m, and \e[4m\e[31m$(vector[1])\e[0m is a CTE " *
        "declared on this query.\n  Since #444 a CTE column has its own namespace and is referenced " *
        "with \e[4m\e[32mCTE(\"$(vector[1])\", \"$(rest)\")\e[0m, not with a " *
        "\e[4m\e[31m\"$(vector[1])__$(rest)\"\e[0m path — that spelling now means the model's own " *
        "\e[4m\e[31m$(vector[1])\e[0m field, which does not exist here."))
    end
    # #446: through the shared funnel. This site built the same sentence by hand with UNSORTED field
    # names and a slightly different tail, so a user saw one format when they typo'd the first path
    # segment and another when they typo'd a later one — for the same mistake.
    throw(_unknown_field(instruct.object.model, vector[1]))
  end

  if !m2m_inserted
    # #474: `custom_join` is the BASE model's join-config registry, and this hop only has a config
    # to inherit when it is rooted there. A CTE-rooted hop is not — `join_path` here is `field[1]`,
    # i.e. the CTE NAME, so these two lookups read whatever `cjoin` / `cjoin_on` / `on()` entry
    # happened to share that name and handed the CTE's join that entry's type and predicates. That
    # was #447's first two symptoms; the third was `_insert_join` claiming the CTE name in
    # `row_path`. Skipping the lookups and namespacing the key makes all three unrepresentable —
    # a CTE has no join config by construction, and its join type comes from `cte_dict["join_type"]`
    # set in the `cte` branch above.
    join_type_override = cte ? nothing : _get_join_type_override(instruct.object, join_path)
    join_type_override !== nothing && (row_join["how"] = join_type_override)

    join_filters = cte ? nothing : _get_join_filters(instruct.object, join_path)
    if join_filters !== nothing && !isempty(join_filters)
      @pormg_debug false
      row_join["on_conditions"] = join_filters
    end

    tb_alias = _insert_join(instruct.row_join, row_join, instruct.row_path, join_path; track_path = !cte)
  end
  
  vector = vector[2:end]  

  @pormg_debug false
  
  while size(vector, 1) > 1
    # get new object
    @pormg_debug false
    join_path = join(field[1:length(field)-length(vector) + 1], "__")
    new_object = foreign_table_name isa PormGModel ? foreign_table_name : getfield(foreing_table_module, foreign_table_name |> Symbol)
    first_column = _resolve_fk_short_form(new_object, vector[1])

    # #27: a non-terminal JSON field reached through FK joins (e.g. `fk__payload__key`) is a value
    # extraction on the joined table's alias, not a further hop. size(vector) > 1 here, so the
    # trailing segments are a JSON path.
    if haskey(new_object.fields, first_column) && Models.is_json_field(new_object.fields[first_column])
      return _render_json_lookup(instruct, tb_alias, new_object.fields[first_column], first_column, String.(vector[2:end]), field; cte=cte)
    end

    # Create a new Dict for this join to avoid mutating previously inserted joins
    prev_how = row_join["how"]
    prev_b = row_join["b"]
    row_join = sizehint!(Dict{String, Union{String, Vector{FilterType}}}(), 8)

    # Track whether the reverse-join branch already advanced vector
    _reverse_advanced = false
    _m2m_inserted = false

    if haskey(new_object.fields, first_column) && Models.is_many_to_many_field(new_object.fields[first_column])
      relation = Models.get_many_to_many_relation(new_object, first_column)
      tb_alias, row_join, foreign_model, last_field = _apply_many_to_many_branch(
        relation, instruct, prev_b, tb_alias, join_path, vector; previus_how=prev_how, track_path = !cte
      )
      foreign_table_name = foreign_model
      _m2m_inserted = true
    elseif first_column in new_object.field_names
      first_field = new_object.fields[first_column]
      !hasfield(typeof(first_field), :to) && throw(QueryBuildError("Invalid field path: the column $(first_column) is a field from $(new_object.name), but it does not have a foreign key"))
      row_join["a"] = prev_b
      row_join["alias_a"] = tb_alias      
      # `first_field`, not a second `new_object.fields[first_column]` lookup — same object, and it is
      # the one the `hasfield(:to)` guard above already vetted and `fk_target_column` reads below.
      row_join["how"] = _determine_join_type(first_field, previus_how=prev_how, second_fild_name= size(vector, 1) > 1 ? vector[2] : nothing)
      next_target = first_field.to
      if next_target === nothing
        # #197: this used to blame `vector[2]`, but the FK-less column is `first_column`.
        throw(QueryBuildError("Invalid field path: the column $(first_column) in $(new_object.name) does not have a foreign key target"))
      end
      # #388: same single arm as the first hop above — see `_forward_join_model`.
      next_model = next_target isa PormGModel ? next_target :
        _forward_join_model(next_target, foreing_table_module, new_object, first_column)
      row_join["b"] = Models.model_table_name(next_model)
      size(vector, 1) == 2 && (last_field = get(next_model.fields, vector[2], nothing))
      foreign_table_name = next_model
      row_join["alias_b"] = _get_alias_name(instruct) # TODO chage by row_join and test the speed
      # Local FK column and referenced parent column both honor db_column (#50). When `new_object`
      # is a CTE model this stays correct WITHOUT a branch (#376): its fields carry no db_column, so
      # `key_a` resolves to the projection alias the CTE actually exposes, while `key_b` reads the
      # REAL target model and keeps its physical column — the two halves of the same contract.
      row_join["key_b"] = Models.fk_target_column(first_field)
      row_join["key_a"] = Models.field_db_column(first_field, first_column)
    elseif haskey(new_object.related_objects, vector[1])
      related_object = new_object.related_objects[vector[1]]
      if related_object isa Models.ManyToManyRelation
        relation = related_object::Models.ManyToManyRelation
        tb_alias, row_join, foreign_model, last_field = _apply_many_to_many_branch(
          relation, instruct, prev_b, tb_alias, join_path, vector; previus_how=prev_how, reverse=true, track_path = !cte
        )
        foreign_table_name = foreign_model
        _m2m_inserted = true
      else
      # #343: read the resolved child — see the first-hop branch above for why respelling the
      # binding from the logical name cannot work.
      rel = related_object::Models.ReverseRelation
      reverse_model = rel.model_resolved
      length(vector) == 1 && throw(QueryBuildError("Invalid field path: $(vector[1]) is a reverse field, you must inform the column to be selected. Example: ...filter(\"$(vector[1])__column\")"))
      !(vector[2] in reverse_model.field_names) && throw(UnknownFieldError("Invalid field path: the column $(vector[2]) not found in $(reverse_model.name)"))
      row_join["a"] = prev_b
      row_join["alias_a"] = tb_alias
      join_field = reverse_model.fields[String(rel.fk_field)]
      row_join["how"] = _determine_join_type(join_field, previus_how=prev_how, second_fild_name= vector[2])
      size(vector, 1) == 2 && (last_field = get(reverse_model.fields, vector[2], nothing))
      row_join["b"] = _reverse_join_table(reverse_model, String(rel.model_name), instruct.django)

      row_join["alias_b"] = _get_alias_name(instruct)
      # Reverse join: key_a is the parent's referenced column, key_b the child's FK
      # column; both honor db_column (resolved in their own model, no-op without it) (#50).
      row_join["key_a"] = Models.model_column(new_object, String(rel.target_pk))
      row_join["key_b"] = Models.model_column(reverse_model, String(rel.fk_field))
      # #74: a reverse foreign key (one-to-many) makes the child table the many-side.
      row_join["to_many"] = "1"
      foreign_table_name = reverse_model
      vector = vector[2:end]
      _reverse_advanced = true
      end

    else
      throw(UnknownFieldError("Invalid field path: the column $(vector[1]) not found in $(new_object.name)"))
    end

    @pormg_debug false   
    if !_m2m_inserted
      # #474: same gate as the first hop above, and it is needed here too rather than only there.
      # `join_path` is recomputed as `"<root>__<seg>"`, so a CTE-rooted deep path produces
      # `"ev__parent"` — which collides with an `on("ev__parent", …)` entry whenever the base model
      # also has a relation named `ev`. Hops past the first also walk the CTE's OWN model, whose
      # field names are a different namespace from the base model's join keys entirely.
      join_type_override = cte ? nothing : _get_join_type_override(instruct.object, join_path)
      join_type_override !== nothing && (row_join["how"] = join_type_override)

      join_filters = cte ? nothing : _get_join_filters(instruct.object, join_path)
      if join_filters !== nothing && !isempty(join_filters)
        row_join["on_conditions"] = join_filters
      end

      tb_alias = _insert_join(instruct.row_join, row_join, instruct.row_path, join_path; track_path = !cte)
    end

    # Only advance vector for forward-FK joins; reverse joins already advanced above
    if !_reverse_advanced
      vector = vector[2:end]
    end

  end

  # tb_alias is the last table alias in the join ex. tb_1
  # last_column is the last column in the join ex. last_login
  # vector is the full path to the column ex. user__last_login__date (including functions (except the suffix))

  # @pormg_debug

  # println("$(join(field, "__"))")
  # functions must be processed here
  # `tab_field_cache` is `Dict{MemoKey,PormGField}` (#474), so a `nothing` here would raise a MethodError
  # BEFORE `_solve_field` below could report the real problem — which is the whole point of letting
  # the lookups above fall through. Guarding the write is what makes that fall-through reach the
  # typed error. Nothing depends on the entry existing: every reader is `haskey`-gated.
  # #474: namespaced for a CTE-rooted path — same argument as `row_path` and `instruct.cache`.
  last_field !== nothing && (instruct.tab_field_cache[_join_path_key(join(field, "__"), cte)] = last_field)
  return string(quote_identifier(tb_alias, instruct.connection), ".", _solve_field(vector[end], foreing_table_module, foreign_table_name, instruct))
  
end