module pending_migrations

import PormG.Migrations
import OrderedCollections: OrderedDict

# table: result
result = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS result (
  "fastestlapspeed" float NULL,
  "points" float NOT NULL,
  "raceid" bigint NOT NULL,
  "number" integer NULL,
  "time" varchar(250) NULL,
  "fastestlaptime" time NULL,
  "driverid" bigint NOT NULL,
  "position" integer NULL,
  "laps" integer NOT NULL,
  "rank" integer NULL,
  "statusid" bigint NOT NULL,
  "resultid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "fastestlap" integer NULL,
  "grid" integer NOT NULL,
  "milliseconds" integer NULL,
  "positionorder" integer NOT NULL,
  "positiontext" varchar(250) NOT NULL,
  "constructorid" bigint NOT NULL
);""",
 
"New foreign key: raceid" =>
 """ALTER TABLE result ADD CONSTRAINT "result_raceid_yurfvufc_fk" FOREIGN KEY ("raceid") REFERENCES "race" ("raceid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on raceid" =>
 """CREATE INDEX IF NOT EXISTS "result_raceid_yurfvufc_idx" ON "result" ("raceid");""",
 
"New foreign key: driverid" =>
 """ALTER TABLE result ADD CONSTRAINT "result_driverid_r4m77pdj_fk" FOREIGN KEY ("driverid") REFERENCES "driver" ("driverid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on driverid" =>
 """CREATE INDEX IF NOT EXISTS "result_driverid_r4m77pdj_idx" ON "result" ("driverid");""",
 
"New foreign key: statusid" =>
 """ALTER TABLE result ADD CONSTRAINT "result_statusid_v8leygun_fk" FOREIGN KEY ("statusid") REFERENCES "status" ("statusid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on statusid" =>
 """CREATE INDEX IF NOT EXISTS "result_statusid_v8leygun_idx" ON "result" ("statusid");""",
 
"New foreign key: constructorid" =>
 """ALTER TABLE result ADD CONSTRAINT "result_constructorid_uqe6rwcb_fk" FOREIGN KEY ("constructorid") REFERENCES "constructor" ("constructorid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on constructorid" =>
 """CREATE INDEX IF NOT EXISTS "result_constructorid_uqe6rwcb_idx" ON "result" ("constructorid");""")

# table: circuit
circuit = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS circuit (
  "lat" float NOT NULL,
  "circuitid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(250) NOT NULL,
  "location" varchar(250) NOT NULL,
  "alt" integer NOT NULL,
  "lng" float NOT NULL,
  "circuitref" varchar(250) NOT NULL,
  "url" varchar(250) NOT NULL,
  "country" varchar(250) NOT NULL
);""")

# table: status
status = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS status (
  "statusid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "status" varchar(250) NOT NULL
);""")

# table: constructor
constructor = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS constructor (
  "name" varchar(250) NOT NULL,
  "nationality" varchar(250) NOT NULL,
  "constructorref" varchar(250) NOT NULL,
  "url" varchar(250) NOT NULL,
  "constructorid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY
);""")

# table: driver
driver = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS driver (
  "number" integer NULL,
  "surname" varchar(250) NOT NULL,
  "driverid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "driverref" varchar(250) NOT NULL,
  "nationality" varchar(250) NOT NULL,
  "dob" date NOT NULL,
  "code" varchar(250) NOT NULL,
  "url" varchar(250) NOT NULL,
  "forename" varchar(250) NOT NULL
);""")

# table: race
race = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS race (
  "raceid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "fp2_date" date NULL,
  "time" time NULL,
  "sprint_date" date NULL,
  "quali_date" date NULL,
  "name" varchar(250) NOT NULL,
  "fp3_time" time NULL,
  "round" integer NOT NULL,
  "fp1_date" date NULL,
  "fp2_time" time NULL,
  "year" integer NOT NULL,
  "date" date NOT NULL,
  "url" varchar(250) NOT NULL,
  "fp3_date" date NULL,
  "quali_time" time NULL,
  "circuitid" bigint NOT NULL,
  "fp1_time" time NULL,
  "sprint_time" time NULL
);""",
 
"New foreign key: circuitid" =>
 """ALTER TABLE race ADD CONSTRAINT "race_circuitid_hovphix6_fk" FOREIGN KEY ("circuitid") REFERENCES "circuit" ("circuitid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on circuitid" =>
 """CREATE INDEX IF NOT EXISTS "race_circuitid_hovphix6_idx" ON "race" ("circuitid");""")

# table: just_a_test_deletion
just_a_test_deletion = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS just_a_test_deletion (
  "name" varchar(250) NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "test_result" bigint NOT NULL
);""",
 
"New foreign key: test_result" =>
 """ALTER TABLE just_a_test_deletion ADD CONSTRAINT "just_a_test_deletion_test_result_61jtvbv2_fk" FOREIGN KEY ("test_result") REFERENCES "result" ("resultid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on test_result" =>
 """CREATE INDEX IF NOT EXISTS "just_a_test_deletion_test_result_61jtvbv2_idx" ON "just_a_test_deletion" ("test_result");""")

end
