module pending_migrations

import PormG.Migrations
import OrderedCollections: OrderedDict

# table: just_a_test_deletion
just_a_test_deletion = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS just_a_test_deletion (
  "name" varchar(250) NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "test_result" bigint NOT NULL
);""",
 
"New foreign key: test_result" =>
 """ALTER TABLE just_a_test_deletion ADD CONSTRAINT "just_a_test_deletion_test_result_18tivahc_fk" FOREIGN KEY ("test_result") REFERENCES "result" ("resultid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on test_result" =>
 """CREATE INDEX IF NOT EXISTS "just_a_test_deletion_test_result_18tivahc_idx" ON "just_a_test_deletion" ("test_result");""")

end
