module pending_migrations

import PormG.Migrations
import OrderedCollections: OrderedDict

# table: status
status = OrderedDict{String, String}(
"Rename field: statusid" =>
 """ALTER TABLE "status" RENAME COLUMN "id" TO "statusid";""")

# table: result
result = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS result (
  "fastestlapspeed" float NOT NULL,
  "points" float NOT NULL,
  "raceid" bigint NOT NULL,
  "number" integer NOT NULL,
  "time" varchar(250) NOT NULL,
  "fastestlaptime" varchar(250) NOT NULL,
  "driverid" bigint NOT NULL,
  "position" integer NOT NULL,
  "laps" integer NOT NULL,
  "rank" integer NOT NULL,
  "statusid" bigint NOT NULL,
  "resultid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "fastestlap" integer NOT NULL,
  "grid" integer NOT NULL,
  "milliseconds" integer NOT NULL,
  "positionorder" integer NOT NULL,
  "positiontext" varchar(250) NOT NULL,
  "constructorid" bigint NOT NULL
);""",
 
"New foreign key: raceid" =>
 """ALTER TABLE result ADD CONSTRAINT "result_raceid_07sjfctm_fk" FOREIGN KEY ("raceid") REFERENCES "race" ("raceid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on raceid" =>
 """CREATE INDEX IF NOT EXISTS "result_raceid_07sjfctm_idx" ON "result" ("raceid");""",
 
"New foreign key: driverid" =>
 """ALTER TABLE result ADD CONSTRAINT "result_driverid_wmgwimir_fk" FOREIGN KEY ("driverid") REFERENCES "driver" ("driverid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on driverid" =>
 """CREATE INDEX IF NOT EXISTS "result_driverid_wmgwimir_idx" ON "result" ("driverid");""",
 
"New foreign key: statusid" =>
 """ALTER TABLE result ADD CONSTRAINT "result_statusid_oyi70veu_fk" FOREIGN KEY ("statusid") REFERENCES "status" ("statusid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on statusid" =>
 """CREATE INDEX IF NOT EXISTS "result_statusid_oyi70veu_idx" ON "result" ("statusid");""",
 
"New foreign key: constructorid" =>
 """ALTER TABLE result ADD CONSTRAINT "result_constructorid_ocev57tu_fk" FOREIGN KEY ("constructorid") REFERENCES "constructor" ("constructorid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on constructorid" =>
 """CREATE INDEX IF NOT EXISTS "result_constructorid_ocev57tu_idx" ON "result" ("constructorid");""")

# table: circuit
circuit = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS circuit (
  "lat" float NOT NULL,
  "circuitid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(250) NOT NULL,
  "location" varchar(250) NOT NULL,
  "alt" integer NOT NULL,
  "lng" float NOT NULL,
  "circuitref" varchar(250) NOT NULL,
  "url" varchar(250) NOT NULL,
  "country" varchar(250) NOT NULL
);""")

# table: constructor
constructor = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS constructor (
  "name" varchar(250) NOT NULL,
  "nationality" varchar(250) NOT NULL,
  "constructorref" varchar(250) NOT NULL,
  "url" varchar(250) NOT NULL,
  "constructorid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY
);""")

# table: driver
driver = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS driver (
  "number" integer NOT NULL,
  "surname" varchar(250) NOT NULL,
  "driverid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "driverref" varchar(250) NOT NULL,
  "nationality" varchar(250) NOT NULL,
  "dob" date NOT NULL,
  "code" varchar(250) NOT NULL,
  "url" varchar(250) NOT NULL,
  "forename" varchar(250) NOT NULL
);""")

# table: race
race = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS race (
  "raceid" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "fp2_date" date NOT NULL,
  "time" time NOT NULL,
  "sprint_date" date NOT NULL,
  "quali_date" date NOT NULL,
  "name" varchar(250) NOT NULL,
  "fp3_time" time NOT NULL,
  "round" integer NOT NULL,
  "fp1_date" date NOT NULL,
  "fp2_time" time NOT NULL,
  "year" integer NOT NULL,
  "date" date NOT NULL,
  "url" varchar(250) NOT NULL,
  "fp3_date" date NOT NULL,
  "quali_time" time NOT NULL,
  "circuitid" bigint NOT NULL,
  "fp1_time" time NOT NULL,
  "sprint_time" time NOT NULL
);""",
 
"New foreign key: circuitid" =>
 """ALTER TABLE race ADD CONSTRAINT "race_circuitid_qe8pmyfk_fk" FOREIGN KEY ("circuitid") REFERENCES "circuit" ("circuitid") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on circuitid" =>
 """CREATE INDEX IF NOT EXISTS "race_circuitid_qe8pmyfk_idx" ON "race" ("circuitid");""")

end
