# GENERATED by test/unit/test_join_condition_matrix.jl with PORMG_JCM_RECORD=1 — do not edit by hand.
# One entry per (cell, engine): what PormG renders or refuses. A diff here is a behaviour change (#977).
const _JCM_EXPECTED = Dict{Tuple{String,Symbol},Any}(
  ("P1 on first hop/bare pair", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \$1", params = Any[5], join = nothing),
  ("P1 on first hop/bare pair", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = ?", params = Any[5], join = Any[5]),
  ("P1 on first hop/already-prefixed", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \$1", params = Any[5], join = nothing),
  ("P1 on first hop/already-prefixed", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = ?", params = Any[5], join = Any[5]),
  ("P1 on first hop/lookup", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" >= \$1", params = Any[5], join = nothing),
  ("P1 on first hop/lookup", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" >= ?", params = Any[5], join = Any[5]),
  ("P1 on first hop/Q", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = \$1 AND \"Tb_1\".\"number\" < \$2)", params = Any[5, 9], join = nothing),
  ("P1 on first hop/Q", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = ? AND \"Tb_1\".\"number\" < ?)", params = Any[5, 9], join = Any[5, 9]),
  ("P1 on first hop/Qor", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = \$1 OR \"Tb_1\".\"number\" = \$2)", params = Any[5, 7], join = nothing),
  ("P1 on first hop/Qor", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = ? OR \"Tb_1\".\"number\" = ?)", params = Any[5, 7], join = Any[5, 7]),
  ("P1 on first hop/OP", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" > \$1", params = Any[5], join = nothing),
  ("P1 on first hop/OP", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" > ?", params = Any[5], join = Any[5]),
  ("P1 on first hop/pair, F base rhs", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \"Tb\".\"number\"", params = Any[], join = nothing),
  ("P1 on first hop/pair, F base rhs", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \"Tb\".\"number\"", params = Any[], join = Any[]),
  ("P1 on first hop/F == F", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = \"Tb\".\"number\")", params = Any[], join = nothing),
  ("P1 on first hop/F == F", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = \"Tb\".\"number\")", params = Any[], join = Any[]),
  ("P1 on first hop/F arithmetic", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND ((\"Tb_1\".\"number\" + \$1::bigint) > \$2::bigint)", params = Any[1, 3], join = nothing),
  ("P1 on first hop/F arithmetic", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND ((\"Tb_1\".\"number\" + ?) > ?)", params = Any[1, 3], join = Any[1, 3]),
  ("P1 on first hop/function lhs", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (ABS((\"Tb_1\".\"number\")::numeric) > \$1::bigint)", params = Any[0], join = nothing),
  ("P1 on first hop/function lhs", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (ABS(\"Tb_1\".\"number\") > ?)", params = Any[0], join = Any[0]),
  ("P1 on first hop/Case lhs", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (CASE WHEN \"Tb_1\".\"number\" > \$1 THEN \"Tb_1\".\"number\" ELSE \"Tb_1\".\"number\" END > \$2::bigint)", params = Any[5, 1], join = nothing),
  ("P1 on first hop/Case lhs", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (CASE WHEN \"Tb_1\".\"number\" > ? THEN \"Tb_1\".\"number\" ELSE \"Tb_1\".\"number\" END > ?)", params = Any[5, 1], join = Any[5, 1]),
  ("P1 on first hop/rhs own path", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \"Tb_1\".\"number\"", params = Any[], join = nothing),
  ("P1 on first hop/rhs own path", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \"Tb_1\".\"number\"", params = Any[], join = Any[]),
  ("P1 on first hop/Subquery, base OuterRef", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = (SELECT MAX(\"R1\".\"number\") as \"mx\" FROM \"driver\" as \"R1\" WHERE \"R1\".\"driverid\" = \"Tb\".\"driverid\" )", params = Any[], join = nothing),
  ("P1 on first hop/Subquery, base OuterRef", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = (SELECT MAX(\"R1\".\"number\") as \"mx\" FROM \"driver\" as \"R1\" WHERE \"R1\".\"driverid\" = \"Tb\".\"driverid\" )", params = Any[], join = Any[]),
  ("P1 on first hop/Exists, base OuterRef", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (EXISTS (SELECT 1 FROM \"constructor\" as \"R1\" WHERE \"R1\".\"constructorid\" = \"Tb\".\"constructorid\" LIMIT 1))", params = Any[], join = nothing),
  ("P1 on first hop/Exists, base OuterRef", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (EXISTS (SELECT 1 FROM \"constructor\" as \"R1\" WHERE \"R1\".\"constructorid\" = \"Tb\".\"constructorid\" LIMIT 1))", params = Any[], join = Any[]),
  ("P2 on deep hop/bare pair", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = \$1", params = Any[5], join = nothing),
  ("P2 on deep hop/bare pair", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = ?", params = Any[5], join = Any[5]),
  ("P2 on deep hop/already-prefixed", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = \$1", params = Any[5], join = nothing),
  ("P2 on deep hop/already-prefixed", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = ?", params = Any[5], join = Any[5]),
  ("P2 on deep hop/lookup", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" >= \$1", params = Any[5], join = nothing),
  ("P2 on deep hop/lookup", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" >= ?", params = Any[5], join = Any[5]),
  ("P2 on deep hop/Q", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (\"Tb_2\".\"number\" = \$1 AND \"Tb_2\".\"number\" < \$2)", params = Any[5, 9], join = nothing),
  ("P2 on deep hop/Q", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (\"Tb_2\".\"number\" = ? AND \"Tb_2\".\"number\" < ?)", params = Any[5, 9], join = Any[5, 9]),
  ("P2 on deep hop/Qor", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (\"Tb_2\".\"number\" = \$1 OR \"Tb_2\".\"number\" = \$2)", params = Any[5, 7], join = nothing),
  ("P2 on deep hop/Qor", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (\"Tb_2\".\"number\" = ? OR \"Tb_2\".\"number\" = ?)", params = Any[5, 7], join = Any[5, 7]),
  ("P2 on deep hop/OP", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" > \$1", params = Any[5], join = nothing),
  ("P2 on deep hop/OP", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" > ?", params = Any[5], join = Any[5]),
  ("P2 on deep hop/pair, F base rhs", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = \"Tb\".\"number\"", params = Any[], join = nothing),
  ("P2 on deep hop/pair, F base rhs", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = \"Tb\".\"number\"", params = Any[], join = Any[]),
  ("P2 on deep hop/F == F", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (\"Tb_2\".\"number\" = \"Tb\".\"number\")", params = Any[], join = nothing),
  ("P2 on deep hop/F == F", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (\"Tb_2\".\"number\" = \"Tb\".\"number\")", params = Any[], join = Any[]),
  ("P2 on deep hop/F arithmetic", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND ((\"Tb_2\".\"number\" + \$1::bigint) > \$2::bigint)", params = Any[1, 3], join = nothing),
  ("P2 on deep hop/F arithmetic", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND ((\"Tb_2\".\"number\" + ?) > ?)", params = Any[1, 3], join = Any[1, 3]),
  ("P2 on deep hop/function lhs", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (ABS((\"Tb_2\".\"number\")::numeric) > \$1::bigint)", params = Any[0], join = nothing),
  ("P2 on deep hop/function lhs", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (ABS(\"Tb_2\".\"number\") > ?)", params = Any[0], join = Any[0]),
  ("P2 on deep hop/Case lhs", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (CASE WHEN \"Tb_2\".\"number\" > \$1 THEN \"Tb_2\".\"number\" ELSE \"Tb_2\".\"number\" END > \$2::bigint)", params = Any[5, 1], join = nothing),
  ("P2 on deep hop/Case lhs", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (CASE WHEN \"Tb_2\".\"number\" > ? THEN \"Tb_2\".\"number\" ELSE \"Tb_2\".\"number\" END > ?)", params = Any[5, 1], join = Any[5, 1]),
  ("P2 on deep hop/rhs own path", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = \"Tb_2\".\"number\"", params = Any[], join = nothing),
  ("P2 on deep hop/rhs own path", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = \"Tb_2\".\"number\"", params = Any[], join = Any[]),
  ("P2 on deep hop/Subquery, base OuterRef", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = (SELECT MAX(\"R1\".\"number\") as \"mx\" FROM \"driver\" as \"R1\" WHERE \"R1\".\"driverid\" = \"Tb\".\"driverid\" )", params = Any[], join = nothing),
  ("P2 on deep hop/Subquery, base OuterRef", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = (SELECT MAX(\"R1\".\"number\") as \"mx\" FROM \"driver\" as \"R1\" WHERE \"R1\".\"driverid\" = \"Tb\".\"driverid\" )", params = Any[], join = Any[]),
  ("P2 on deep hop/Exists, base OuterRef", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (EXISTS (SELECT 1 FROM \"constructor\" as \"R1\" WHERE \"R1\".\"constructorid\" = \"Tb\".\"constructorid\" LIMIT 1))", params = Any[], join = nothing),
  ("P2 on deep hop/Exists, base OuterRef", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND (EXISTS (SELECT 1 FROM \"constructor\" as \"R1\" WHERE \"R1\".\"constructorid\" = \"Tb\".\"constructorid\" LIMIT 1))", params = Any[], join = Any[]),
  ("P3 cjoin filters/bare pair", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \$1", params = Any[5], join = nothing),
  ("P3 cjoin filters/bare pair", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = ?", params = Any[5], join = Any[5]),
  ("P3 cjoin filters/already-prefixed", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \$1", params = Any[5], join = nothing),
  ("P3 cjoin filters/already-prefixed", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = ?", params = Any[5], join = Any[5]),
  ("P3 cjoin filters/lookup", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" >= \$1", params = Any[5], join = nothing),
  ("P3 cjoin filters/lookup", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" >= ?", params = Any[5], join = Any[5]),
  ("P3 cjoin filters/Q", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = \$1 AND \"Tb_1\".\"number\" < \$2)", params = Any[5, 9], join = nothing),
  ("P3 cjoin filters/Q", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = ? AND \"Tb_1\".\"number\" < ?)", params = Any[5, 9], join = Any[5, 9]),
  ("P3 cjoin filters/Qor", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = \$1 OR \"Tb_1\".\"number\" = \$2)", params = Any[5, 7], join = nothing),
  ("P3 cjoin filters/Qor", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = ? OR \"Tb_1\".\"number\" = ?)", params = Any[5, 7], join = Any[5, 7]),
  ("P3 cjoin filters/OP", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" > \$1", params = Any[5], join = nothing),
  ("P3 cjoin filters/OP", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" > ?", params = Any[5], join = Any[5]),
  ("P3 cjoin filters/pair, F base rhs", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \"Tb\".\"number\"", params = Any[], join = nothing),
  ("P3 cjoin filters/pair, F base rhs", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \"Tb\".\"number\"", params = Any[], join = Any[]),
  ("P3 cjoin filters/F == F", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = \"Tb\".\"number\")", params = Any[], join = nothing),
  ("P3 cjoin filters/F == F", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (\"Tb_1\".\"number\" = \"Tb\".\"number\")", params = Any[], join = Any[]),
  ("P3 cjoin filters/F arithmetic", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND ((\"Tb_1\".\"number\" + \$1::bigint) > \$2::bigint)", params = Any[1, 3], join = nothing),
  ("P3 cjoin filters/F arithmetic", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND ((\"Tb_1\".\"number\" + ?) > ?)", params = Any[1, 3], join = Any[1, 3]),
  ("P3 cjoin filters/function lhs", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (ABS((\"Tb_1\".\"number\")::numeric) > \$1::bigint)", params = Any[0], join = nothing),
  ("P3 cjoin filters/function lhs", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (ABS(\"Tb_1\".\"number\") > ?)", params = Any[0], join = Any[0]),
  ("P3 cjoin filters/Case lhs", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (CASE WHEN \"Tb_1\".\"number\" > \$1 THEN \"Tb_1\".\"number\" ELSE \"Tb_1\".\"number\" END > \$2::bigint)", params = Any[5, 1], join = nothing),
  ("P3 cjoin filters/Case lhs", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (CASE WHEN \"Tb_1\".\"number\" > ? THEN \"Tb_1\".\"number\" ELSE \"Tb_1\".\"number\" END > ?)", params = Any[5, 1], join = Any[5, 1]),
  ("P3 cjoin filters/rhs own path", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \"Tb_1\".\"number\"", params = Any[], join = nothing),
  ("P3 cjoin filters/rhs own path", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = \"Tb_1\".\"number\"", params = Any[], join = Any[]),
  ("P3 cjoin filters/Subquery, base OuterRef", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = (SELECT MAX(\"R1\".\"number\") as \"mx\" FROM \"driver\" as \"R1\" WHERE \"R1\".\"driverid\" = \"Tb\".\"driverid\" )", params = Any[], join = nothing),
  ("P3 cjoin filters/Subquery, base OuterRef", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"number\" = (SELECT MAX(\"R1\".\"number\") as \"mx\" FROM \"driver\" as \"R1\" WHERE \"R1\".\"driverid\" = \"Tb\".\"driverid\" )", params = Any[], join = Any[]),
  ("P3 cjoin filters/Exists, base OuterRef", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (EXISTS (SELECT 1 FROM \"constructor\" as \"R1\" WHERE \"R1\".\"constructorid\" = \"Tb\".\"constructorid\" LIMIT 1))", params = Any[], join = nothing),
  ("P3 cjoin filters/Exists, base OuterRef", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND (EXISTS (SELECT 1 FROM \"constructor\" as \"R1\" WHERE \"R1\".\"constructorid\" = \"Tb\".\"constructorid\" LIMIT 1))", params = Any[], join = Any[]),
  ("P2 on deep hop/rhs ancestor", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = \"Tb_1\".\"number\"", params = Any[], join = nothing),
  ("P2 on deep hop/rhs ancestor", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"grid\" as \"driverid__results__grid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"number\" = \"Tb_1\".\"number\"", params = Any[], join = Any[]),
  ("P1 on first hop/rhs off-path (#962)", :postgres) =>
    (stage = :build, error = "FilterError", message = "F(\"constructorid__constructorid\") reaches 'constructorid', a relation outside the join path 'driverid', so it cannot app"),
  ("P1 on first hop/rhs off-path (#962)", :sqlite) =>
    (stage = :build, error = "FilterError", message = "F(\"constructorid__constructorid\") reaches 'constructorid', a relation outside the join path 'driverid', so it cannot app"),
  ("P1 on first hop/Exists, off-path OuterRef", :postgres) =>
    (stage = :build, error = "FilterError", message = "OuterRef(\"constructorid__name\") reaches 'constructorid', a relation outside the join path 'driverid', so it cannot appea"),
  ("P1 on first hop/Exists, off-path OuterRef", :sqlite) =>
    (stage = :build, error = "FilterError", message = "OuterRef(\"constructorid__name\") reaches 'constructorid', a relation outside the join path 'driverid', so it cannot appea"),
  ("P1 on first hop/rhs off-path, FK short form", :postgres) =>
    (stage = :build, error = "FilterError", message = "F(\"status__name\") reaches 'status_id', a relation outside the join path 'driverid', so it cannot appear in that join's O"),
  ("P1 on first hop/rhs off-path, FK short form", :sqlite) =>
    (stage = :build, error = "FilterError", message = "F(\"status__name\") reaches 'status_id', a relation outside the join path 'driverid', so it cannot appear in that join's O"),
  ("P1 on first hop/rhs off-path in a When over Q", :postgres) =>
    (stage = :build, error = "FilterError", message = "\"constructorid__name\" reaches 'constructorid', a relation outside the join path 'driverid', so it cannot appear in that "),
  ("P1 on first hop/rhs off-path in a When over Q", :sqlite) =>
    (stage = :build, error = "FilterError", message = "\"constructorid__name\" reaches 'constructorid', a relation outside the join path 'driverid', so it cannot appear in that "),
  ("P1 on first hop/rhs off-path OuterRef in a Case branch", :postgres) =>
    (stage = :build, error = "FilterError", message = "OuterRef(\"constructorid__name\") reaches 'constructorid', a relation outside the join path 'driverid', so it cannot appea"),
  ("P1 on first hop/rhs off-path OuterRef in a Case branch", :sqlite) =>
    (stage = :build, error = "FilterError", message = "OuterRef(\"constructorid__name\") reaches 'constructorid', a relation outside the join path 'driverid', so it cannot appea"),
  ("P1 on first hop/CTE handle", :postgres) =>
    (stage = :call, error = "FilterError", message = "CTE(\"ev\", \"sku\") cannot be used in a join ON clause (on(...) / cjoin(...)). A JOIN's ON clause targets the joined MODEL;"),
  ("P1 on first hop/CTE handle", :sqlite) =>
    (stage = :call, error = "FilterError", message = "CTE(\"ev\", \"sku\") cannot be used in a join ON clause (on(...) / cjoin(...)). A JOIN's ON clause targets the joined MODEL;"),
  ("P1 on first hop/Joined handle", :postgres) =>
    (stage = :call, error = "FilterError", message = "Joined(\"d2\", \"number\") cannot be used in a join ON clause (on(...) / cjoin(...)). That clause adds predicates to a join "),
  ("P1 on first hop/Joined handle", :sqlite) =>
    (stage = :call, error = "FilterError", message = "Joined(\"d2\", \"number\") cannot be used in a join ON clause (on(...) / cjoin(...)). That clause adds predicates to a join "),
  ("P1 on first hop/lhs past hop, reverse (#973)", :postgres) =>
    (stage = :call, error = "FilterError", message = "\"results__grid\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__results', past the join path 'driverid'. A "),
  ("P1 on first hop/lhs past hop, reverse (#973)", :sqlite) =>
    (stage = :call, error = "FilterError", message = "\"results__grid\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__results', past the join path 'driverid'. A "),
  ("P1 on first hop/lhs past hop, reverse in Q (#973)", :postgres) =>
    (stage = :call, error = "FilterError", message = "\"results__grid\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__results', past the join path 'driverid'. A "),
  ("P1 on first hop/lhs past hop, reverse in Q (#973)", :sqlite) =>
    (stage = :call, error = "FilterError", message = "\"results__grid\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__results', past the join path 'driverid'. A "),
  ("P1 on first hop/lhs past hop, forward (#973)", :postgres) =>
    (stage = :call, error = "FilterError", message = "\"teamid__name\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__teamid', past the join path 'driverid'. A co"),
  ("P1 on first hop/lhs past hop, forward (#973)", :sqlite) =>
    (stage = :call, error = "FilterError", message = "\"teamid__name\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__teamid', past the join path 'driverid'. A co"),
  ("P3 cjoin filters/lhs past hop, forward (#973)", :postgres) =>
    (stage = :call, error = "FilterError", message = "\"teamid__name\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__teamid', past the join path 'driverid'. A co"),
  ("P3 cjoin filters/lhs past hop, forward (#973)", :sqlite) =>
    (stage = :call, error = "FilterError", message = "\"teamid__name\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__teamid', past the join path 'driverid'. A co"),
  ("P3 cjoin filters/two depths, deep first (#421)", :postgres) =>
    (stage = :call, error = "FilterError", message = "\"teamid__name\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__teamid', past the join path 'driverid'. A co"),
  ("P3 cjoin filters/two depths, deep first (#421)", :sqlite) =>
    (stage = :call, error = "FilterError", message = "\"teamid__name\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__teamid', past the join path 'driverid'. A co"),
  ("P1 on first hop/two depths, one on() per hop", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"name\" as \"driverid__teamid__name\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"code\" = \$1 LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" AND \"Tb_2\".\"name\" = \$2", params = Any["SSS", "ZZZ"], join = nothing),
  ("P1 on first hop/two depths, one on() per hop", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_2\".\"name\" as \"driverid__teamid__name\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"code\" = ? LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" AND \"Tb_2\".\"name\" = ?", params = Any["SSS", "ZZZ"], join = Any["SSS", "ZZZ"]),
  ("P4 cjoin plain column/bare pair", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"grid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" AND \"Tb_1\".\"code\" = \$1", params = Any["X"], join = nothing),
  ("P4 cjoin plain column/bare pair", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"grid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" AND \"Tb_1\".\"code\" = ?", params = Any["X"], join = Any["X"]),
  ("P5a cjoin then on()/bare pair (#974)", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"grid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" AND \"Tb_1\".\"code\" = \$1", params = Any["X"], join = nothing),
  ("P5a cjoin then on()/bare pair (#974)", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"grid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" AND \"Tb_1\".\"code\" = ?", params = Any["X"], join = Any["X"]),
  ("P5b on() then cjoin/bare pair (#974)", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"grid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" AND \"Tb_1\".\"code\" = \$1", params = Any["X"], join = nothing),
  ("P5b on() then cjoin/bare pair (#974)", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"grid__code\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" AND \"Tb_1\".\"code\" = ?", params = Any["X"], join = Any["X"]),
  ("P5c on() plain column, no cjoin/bare pair", :postgres) =>
    (stage = :build, error = "QueryBuildError", message = "Join path 'grid' stops at base field 'grid', which is not a relation. Use .cjoin(..., field=...) first if this path depe"),
  ("P5c on() plain column, no cjoin/bare pair", :sqlite) =>
    (stage = :build, error = "QueryBuildError", message = "Join path 'grid' stops at base field 'grid', which is not a relation. Use .cjoin(..., field=...) first if this path depe"),
  ("P6 on() unreached path/bare pair", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" LEFT JOIN \"constructor\" AS \"Tb_1\" ON \"Tb\".\"constructorid\" = \"Tb_1\".\"constructorid\" AND \"Tb_1\".\"name\" = \$1", params = Any["X"], join = nothing),
  ("P6 on() unreached path/bare pair", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" LEFT JOIN \"constructor\" AS \"Tb_1\" ON \"Tb\".\"constructorid\" = \"Tb_1\".\"constructorid\" AND \"Tb_1\".\"name\" = ?", params = Any["X"], join = Any["X"]),
  ("P6 on() unreached path/INNER", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"constructor\" AS \"Tb_1\" ON \"Tb\".\"constructorid\" = \"Tb_1\".\"constructorid\" AND \"Tb_1\".\"name\" = \$1", params = Any["X"], join = nothing),
  ("P6 on() unreached path/INNER", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"constructor\" AS \"Tb_1\" ON \"Tb\".\"constructorid\" = \"Tb_1\".\"constructorid\" AND \"Tb_1\".\"name\" = ?", params = Any["X"], join = Any["X"]),
  ("P9 on() short form, traversed by field name/INNER", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status_id__name\" FROM \"result\" as \"Tb\" INNER JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"name\" = \$1", params = Any["X"], join = nothing),
  ("P9 on() short form, traversed by field name/INNER", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status_id__name\" FROM \"result\" as \"Tb\" INNER JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"name\" = ?", params = Any["X"], join = Any["X"]),
  ("P9 on() field name, traversed by short form/bare pair", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status__name\" FROM \"result\" as \"Tb\" LEFT JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"name\" = \$1", params = Any["X"], join = nothing),
  ("P9 on() field name, traversed by short form/bare pair", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status__name\" FROM \"result\" as \"Tb\" LEFT JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"name\" = ?", params = Any["X"], join = Any["X"]),
  ("P9 cjoin on FK field, traversed by short form/filters", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status__name\" FROM \"result\" as \"Tb\" INNER JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"name\" = \$1", params = Any["X"], join = nothing),
  ("P9 cjoin on FK field, traversed by short form/filters", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status__name\" FROM \"result\" as \"Tb\" INNER JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"name\" = ?", params = Any["X"], join = Any["X"]),
  ("P9 cjoin on FK field, then on() short form/both conditions", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status__name\" FROM \"result\" as \"Tb\" LEFT JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"name\" = \$1 AND \"Tb_1\".\"statusid\" = \$2", params = Any["Y", 3], join = nothing),
  ("P9 cjoin on FK field, then on() short form/both conditions", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status__name\" FROM \"result\" as \"Tb\" LEFT JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"name\" = ? AND \"Tb_1\".\"statusid\" = ?", params = Any["Y", 3], join = Any["Y", 3]),
  ("P9 on() short form, then cjoin on FK field/both conditions", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status__name\" FROM \"result\" as \"Tb\" LEFT JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"statusid\" = \$1 AND \"Tb_1\".\"name\" = \$2", params = Any[3, "Y"], join = nothing),
  ("P9 on() short form, then cjoin on FK field/both conditions", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"name\" as \"status__name\" FROM \"result\" as \"Tb\" LEFT JOIN \"status\" AS \"Tb_1\" ON \"Tb\".\"status_id\" = \"Tb_1\".\"statusid\" AND \"Tb_1\".\"statusid\" = ? AND \"Tb_1\".\"name\" = ?", params = Any[3, "Y"], join = Any[3, "Y"]),
  ("P8 on() ManyToMany hop/traversed", :postgres) =>
    (stage = :build, error = "QueryBuildError", message = "on(\"driverid__sponsors\", …) crosses the ManyToMany relation 'driverid__sponsors', whose join goes through a link table t"),
  ("P8 on() ManyToMany hop/traversed", :sqlite) =>
    (stage = :build, error = "QueryBuildError", message = "on(\"driverid__sponsors\", …) crosses the ManyToMany relation 'driverid__sponsors', whose join goes through a link table t"),
  ("P8 on() ManyToMany hop/unreached", :postgres) =>
    (stage = :build, error = "QueryBuildError", message = "on(\"driverid__sponsors\", …) crosses the ManyToMany relation 'driverid__sponsors', whose join goes through a link table t"),
  ("P8 on() ManyToMany hop/unreached", :sqlite) =>
    (stage = :build, error = "QueryBuildError", message = "on(\"driverid__sponsors\", …) crosses the ManyToMany relation 'driverid__sponsors', whose join goes through a link table t"),
  ("P7 cjoin_on/Joined anchor + predicate", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"d2\".\"code\" = \$1", params = Any["X"], join = nothing),
  ("P7 cjoin_on/Joined anchor + predicate", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"d2\".\"code\" = ?", params = Any["X"], join = Any["X"]),
  ("P7 cjoin_on/base column against Joined", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"number\" = \"Tb\".\"number\")", params = Any[], join = nothing),
  ("P7 cjoin_on/base column against Joined", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"number\" = \"Tb\".\"number\")", params = Any[], join = Any[]),
  ("P7 cjoin_on/deep path predicate, unreached", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"Tb_1\".\"code\" = \$1", params = Any["X"], join = nothing),
  ("P7 cjoin_on/deep path predicate, unreached", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"Tb_1\".\"code\" = ?", params = Any["X"], join = Any["X"]),
  ("P7 cjoin_on/deep path predicate, projected", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"Tb_1\".\"code\" = \$1", params = Any["X"], join = nothing),
  ("P7 cjoin_on/deep path predicate, projected", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"code\" as \"driverid__code\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"Tb_1\".\"code\" = ?", params = Any["X"], join = Any["X"]),
  ("P7 cjoin_on/deep path predicate, LEFT", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"Tb_1\".\"code\" = \$1", params = Any["X"], join = nothing),
  ("P7 cjoin_on/deep path predicate, LEFT", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"Tb_1\".\"code\" = ?", params = Any["X"], join = Any["X"]),
  ("P7 cjoin_on/reverse path predicate (#992)", :postgres) =>
    (stage = :build, error = "FilterError", message = "\"driverid__results__grid\" in the ON clause of cjoin_on alias d2 crosses the reverse relation 'driverid__results'. PormG "),
  ("P7 cjoin_on/reverse path predicate (#992)", :sqlite) =>
    (stage = :build, error = "FilterError", message = "\"driverid__results__grid\" in the ON clause of cjoin_on alias d2 crosses the reverse relation 'driverid__results'. PormG "),
  ("P7 cjoin_on/ManyToMany path predicate (#992)", :postgres) =>
    (stage = :build, error = "FilterError", message = "\"driverid__sponsors__name\" in the ON clause of cjoin_on alias d2 crosses the ManyToMany relation 'driverid__sponsors'. P"),
  ("P7 cjoin_on/ManyToMany path predicate (#992)", :sqlite) =>
    (stage = :build, error = "FilterError", message = "\"driverid__sponsors__name\" in the ON clause of cjoin_on alias d2 crosses the ManyToMany relation 'driverid__sponsors'. P"),
  ("P7 cjoin_on/Joined against deep path F", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"code\" = \"Tb_1\".\"code\")", params = Any[], join = nothing),
  ("P7 cjoin_on/Joined against deep path F", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"code\" = \"Tb_1\".\"code\")", params = Any[], join = Any[]),
  ("P7 cjoin_on/two rows bind, path first (#421)", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"d2\" ON \"Tb_1\".\"code\" = \$1 AND (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"d2\".\"code\" = \$2", params = Any["A", "B"], join = nothing),
  ("P7 cjoin_on/two rows bind, path first (#421)", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"d2\" ON \"Tb_1\".\"code\" = ? AND (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"d2\".\"code\" = ?", params = Any["A", "B"], join = Any["A", "B"]),
  ("P7 cjoin_on/second alias names the first", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"d1\" ON (\"d1\".\"driverid\" = \"Tb\".\"driverid\") INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"number\" = \"d1\".\"number\")", params = Any[], join = nothing),
  ("P7 cjoin_on/second alias names the first", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"d1\" ON (\"d1\".\"driverid\" = \"Tb\".\"driverid\") INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"number\" = \"d1\".\"number\")", params = Any[], join = Any[]),
  ("P7 cjoin_on/first alias names the second", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") INNER JOIN \"driver\" AS \"d1\" ON (\"d1\".\"number\" = \"d2\".\"number\")", params = Any[], join = nothing),
  ("P7 cjoin_on/first alias names the second", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") INNER JOIN \"driver\" AS \"d1\" ON (\"d1\".\"number\" = \"d2\".\"number\")", params = Any[], join = Any[]),
  ("P7 cjoin_on/alias cycle", :postgres) =>
    (stage = :build, error = "QueryBuildError", message = "The cjoin_on ON clauses of d1 and d2 name each other, so no join order emits every alias before the ON clauses that refe"),
  ("P7 cjoin_on/alias cycle", :sqlite) =>
    (stage = :build, error = "QueryBuildError", message = "The cjoin_on ON clauses of d1 and d2 name each other, so no join order emits every alias before the ON clauses that refe"),
  ("P7 cjoin_on/no reference to its own alias (#448)", :postgres) =>
    (stage = :build, error = "QueryBuildError", message = "The ON clause built for d2 never references d2, so the join is not constrained by it: every driver row would pair with e"),
  ("P7 cjoin_on/no reference to its own alias (#448)", :sqlite) =>
    (stage = :build, error = "QueryBuildError", message = "The ON clause built for d2 never references d2, so the join is not constrained by it: every driver row would pair with e"),
)
