# GENERATED by test/unit/test_join_cardinality_matrix.jl with PORMG_JCARD_RECORD=1 — do not edit by hand.
# One entry per (cell, engine): what PormG renders or refuses. A diff here is a behaviour change (#1002).
const _JCARD_EXPECTED = Dict{Tuple{String,Symbol},Any}(
  ("values/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"name\" as \"teamid__name\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\""),
  ("values/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"name\" as \"teamid__name\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\""),
  ("values/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"grid\" as \"results__grid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\""),
  ("values/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"grid\" as \"results__grid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\""),
  ("values/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"bio\" as \"profile__bio\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\""),
  ("values/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"bio\" as \"profile__bio\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\""),
  ("values/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_2\".\"name\" as \"sponsors__name\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\""),
  ("values/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_2\".\"name\" as \"sponsors__name\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\""),
  ("filter/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1"),
  ("filter/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ?"),
  ("filter/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1"),
  ("filter/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ?"),
  ("filter/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1"),
  ("filter/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ?"),
  ("filter/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1"),
  ("filter/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ?"),
  ("order_by/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" ORDER BY \"Tb_1\".\"name\" ASC NULLS LAST"),
  ("order_by/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" ORDER BY \"Tb_1\".\"name\" ASC NULLS LAST"),
  ("order_by/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" ORDER BY \"Tb_1\".\"grid\" ASC NULLS LAST"),
  ("order_by/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" ORDER BY \"Tb_1\".\"grid\" ASC NULLS LAST"),
  ("order_by/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" ORDER BY \"Tb_1\".\"bio\" ASC NULLS LAST"),
  ("order_by/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" ORDER BY \"Tb_1\".\"bio\" ASC NULLS LAST"),
  ("order_by/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" ORDER BY \"Tb_2\".\"name\" ASC NULLS LAST"),
  ("order_by/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" ORDER BY \"Tb_2\".\"name\" ASC NULLS LAST"),
  ("filter + distinct()/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1"),
  ("filter + distinct()/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ?"),
  ("filter + distinct()/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1"),
  ("filter + distinct()/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ?"),
  ("filter + distinct()/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1"),
  ("filter + distinct()/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ?"),
  ("filter + distinct()/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1"),
  ("filter + distinct()/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ?"),
  ("filter + values same path/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"name\" as \"teamid__name\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1"),
  ("filter + values same path/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"name\" as \"teamid__name\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ?"),
  ("filter + values same path/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"grid\" as \"results__grid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1"),
  ("filter + values same path/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"grid\" as \"results__grid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ?"),
  ("filter + values same path/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"bio\" as \"profile__bio\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1"),
  ("filter + values same path/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"bio\" as \"profile__bio\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ?"),
  ("filter + values same path/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_2\".\"name\" as \"sponsors__name\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1"),
  ("filter + values same path/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_2\".\"name\" as \"sponsors__name\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ?"),
  ("filter + Qor/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE (\"Tb_1\".\"name\" = \$1 OR \"Tb\".\"number\" = \$2)"),
  ("filter + Qor/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE (\"Tb_1\".\"name\" = ? OR \"Tb\".\"number\" = ?)"),
  ("filter + Qor/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE (\"Tb_1\".\"grid\" = \$1 OR \"Tb\".\"number\" = \$2)"),
  ("filter + Qor/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE (\"Tb_1\".\"grid\" = ? OR \"Tb\".\"number\" = ?)"),
  ("filter + Qor/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE (\"Tb_1\".\"bio\" = \$1 OR \"Tb\".\"number\" = \$2)"),
  ("filter + Qor/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE (\"Tb_1\".\"bio\" = ? OR \"Tb\".\"number\" = ?)"),
  ("filter + Qor/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE (\"Tb_2\".\"name\" = \$1 OR \"Tb\".\"number\" = \$2)"),
  ("filter + Qor/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE (\"Tb_2\".\"name\" = ? OR \"Tb\".\"number\" = ?)"),
  ("filter + limit/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1 LIMIT \$2"),
  ("filter + limit/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ? LIMIT ?"),
  ("filter + limit/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1 LIMIT \$2"),
  ("filter + limit/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ? LIMIT ?"),
  ("filter + limit/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1 LIMIT \$2"),
  ("filter + limit/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ? LIMIT ?"),
  ("filter + limit/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1 LIMIT \$2"),
  ("filter + limit/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ? LIMIT ?"),
  ("count()/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1"),
  ("count()/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ?"),
  ("count()/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1"),
  ("count()/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ?"),
  ("count()/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1"),
  ("count()/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ?"),
  ("count()/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1"),
  ("count()/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ?"),
  ("count(distinct = true)/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM ( SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1 ) as \"__pormg_distinct_count\""),
  ("count(distinct = true)/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM ( SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ? ) as \"__pormg_distinct_count\""),
  ("count(distinct = true)/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM ( SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1 ) as \"__pormg_distinct_count\""),
  ("count(distinct = true)/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM ( SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ? ) as \"__pormg_distinct_count\""),
  ("count(distinct = true)/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM ( SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1 ) as \"__pormg_distinct_count\""),
  ("count(distinct = true)/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM ( SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ? ) as \"__pormg_distinct_count\""),
  ("count(distinct = true)/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM ( SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1 ) as \"__pormg_distinct_count\""),
  ("count(distinct = true)/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM ( SELECT DISTINCT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ? ) as \"__pormg_distinct_count\""),
  ("count() over values same path/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1"),
  ("count() over values same path/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ?"),
  ("count() over values same path/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1"),
  ("count() over values same path/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ?"),
  ("count() over values same path/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1"),
  ("count() over values same path/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ?"),
  ("count() over values same path/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1"),
  ("count() over values same path/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT COUNT(*) FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ?"),
  ("exists()/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1 LIMIT 1"),
  ("exists()/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ? LIMIT 1"),
  ("exists()/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1 LIMIT 1"),
  ("exists()/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ? LIMIT 1"),
  ("exists()/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1 LIMIT 1"),
  ("exists()/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ? LIMIT 1"),
  ("exists()/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1 LIMIT 1"),
  ("exists()/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ? LIMIT 1"),
  ("exists() with offset/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1 LIMIT 1 OFFSET \$2"),
  ("exists() with offset/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ? LIMIT 1 OFFSET ?"),
  ("exists() with offset/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1 LIMIT 1 OFFSET \$2"),
  ("exists() with offset/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ? LIMIT 1 OFFSET ?"),
  ("exists() with offset/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1 LIMIT 1 OFFSET \$2"),
  ("exists() with offset/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ? LIMIT 1 OFFSET ?"),
  ("exists() with offset/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1 LIMIT 1 OFFSET \$2"),
  ("exists() with offset/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT 1 FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ? LIMIT 1 OFFSET ?"),
  ("aggregate()/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT MAX(\"Tb\".\"number\") as \"n\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1"),
  ("aggregate()/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT MAX(\"Tb\".\"number\") as \"n\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ?"),
  ("aggregate()/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT MAX(\"Tb\".\"number\") as \"n\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1"),
  ("aggregate()/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT MAX(\"Tb\".\"number\") as \"n\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ?"),
  ("aggregate()/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT MAX(\"Tb\".\"number\") as \"n\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = \$1"),
  ("aggregate()/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT MAX(\"Tb\".\"number\") as \"n\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"bio\" = ?"),
  ("aggregate()/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT MAX(\"Tb\".\"number\") as \"n\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = \$1"),
  ("aggregate()/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT MAX(\"Tb\".\"number\") as \"n\" FROM \"driver\" as \"Tb\" INNER JOIN \"driver_sponsors\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_2\" ON \"Tb_1\".\"sponsor_sponsorid\" = \"Tb_2\".\"sponsorid\" WHERE \"Tb_2\".\"name\" = ?"),
  ("grouped Count/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", COUNT(\"Tb\".\"driverid\") as \"n\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = \$1 GROUP BY 1"),
  ("grouped Count/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", COUNT(\"Tb\".\"driverid\") as \"n\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" WHERE \"Tb_1\".\"name\" = ? GROUP BY 1"),
  ("grouped Count/reverse", :postgres) =>
    (stage = :build, error = "QueryBuildError", message = "PormG fan-out guard (#74): the aggregate n is inflated because it aggregates a column from a table that a to-many join r"),
  ("grouped Count/reverse", :sqlite) =>
    (stage = :build, error = "QueryBuildError", message = "PormG fan-out guard (#74): the aggregate n is inflated because it aggregates a column from a table that a to-many join r"),
  ("grouped Count/reverse OneToOne", :postgres) =>
    (stage = :build, error = "QueryBuildError", message = "PormG fan-out guard (#74): the aggregate n is inflated because it aggregates a column from a table that a to-many join r"),
  ("grouped Count/reverse OneToOne", :sqlite) =>
    (stage = :build, error = "QueryBuildError", message = "PormG fan-out guard (#74): the aggregate n is inflated because it aggregates a column from a table that a to-many join r"),
  ("grouped Count/ManyToMany", :postgres) =>
    (stage = :build, error = "QueryBuildError", message = "PormG fan-out guard (#74): the aggregate n is inflated because it aggregates a column from a table that a to-many join r"),
  ("grouped Count/ManyToMany", :sqlite) =>
    (stage = :build, error = "QueryBuildError", message = "PormG fan-out guard (#74): the aggregate n is inflated because it aggregates a column from a table that a to-many join r"),
  ("Exists() subquery/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"name\" = \$1 LIMIT 1)"),
  ("Exists() subquery/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"name\" = ? LIMIT 1)"),
  ("Exists() subquery/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"grid\" = \$1 LIMIT 1)"),
  ("Exists() subquery/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"grid\" = ? LIMIT 1)"),
  ("Exists() subquery/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"bio\" = \$1 LIMIT 1)"),
  ("Exists() subquery/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"bio\" = ? LIMIT 1)"),
  ("Exists() subquery/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_2\".\"name\" = \$1 LIMIT 1)"),
  ("Exists() subquery/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_2\".\"name\" = ? LIMIT 1)"),
  ("Exists() subquery with offset/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"name\" = \$1 LIMIT 1 OFFSET \$2)"),
  ("Exists() subquery with offset/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"name\" = ? LIMIT 1 OFFSET ?)"),
  ("Exists() subquery with offset/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"grid\" = \$1 LIMIT 1 OFFSET \$2)"),
  ("Exists() subquery with offset/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"grid\" = ? LIMIT 1 OFFSET ?)"),
  ("Exists() subquery with offset/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"bio\" = \$1 LIMIT 1 OFFSET \$2)"),
  ("Exists() subquery with offset/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"bio\" = ? LIMIT 1 OFFSET ?)"),
  ("Exists() subquery with offset/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_2\".\"name\" = \$1 LIMIT 1 OFFSET \$2)"),
  ("Exists() subquery with offset/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE EXISTS (SELECT 1 FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_2\".\"name\" = ? LIMIT 1 OFFSET ?)"),
  ("__@in subquery/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1_1\".\"name\" = \$1 )"),
  ("__@in subquery/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1_1\".\"name\" = ? )"),
  ("__@in subquery/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1_1\".\"grid\" = \$1 )"),
  ("__@in subquery/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1_1\".\"grid\" = ? )"),
  ("__@in subquery/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1_1\".\"bio\" = \$1 )"),
  ("__@in subquery/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1_1\".\"bio\" = ? )"),
  ("__@in subquery/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1_2\".\"name\" = \$1 )"),
  ("__@in subquery/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1_2\".\"name\" = ? )"),
  ("__@in subquery, sliced/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1_1\".\"name\" = \$1 LIMIT \$2 )"),
  ("__@in subquery, sliced/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1_1\".\"name\" = ? LIMIT ? )"),
  ("__@in subquery, sliced/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1_1\".\"grid\" = \$1 LIMIT \$2 )"),
  ("__@in subquery, sliced/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1_1\".\"grid\" = ? LIMIT ? )"),
  ("__@in subquery, sliced/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1_1\".\"bio\" = \$1 LIMIT \$2 )"),
  ("__@in subquery, sliced/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1_1\".\"bio\" = ? LIMIT ? )"),
  ("__@in subquery, sliced/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1_2\".\"name\" = \$1 LIMIT \$2 )"),
  ("__@in subquery, sliced/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" WHERE \"Tb\".\"teamid\" IN (SELECT \"R1\".\"teamid\" as \"teamid\" FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1_2\".\"name\" = ? LIMIT ? )"),
  ("scalar Subquery/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"code\" as \"code\" FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"name\" = \$1 LIMIT \$2 ) as \"c\" FROM \"team\" as \"Tb\""),
  ("scalar Subquery/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"code\" as \"code\" FROM \"driver\" as \"R1\" LEFT JOIN \"team\" AS \"R1_1\" ON \"R1\".\"teamid\" = \"R1_1\".\"teamid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"name\" = ? LIMIT ? ) as \"c\" FROM \"team\" as \"Tb\""),
  ("scalar Subquery/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"code\" as \"code\" FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"grid\" = \$1 LIMIT \$2 ) as \"c\" FROM \"team\" as \"Tb\""),
  ("scalar Subquery/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"code\" as \"code\" FROM \"driver\" as \"R1\" INNER JOIN \"result\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"grid\" = ? LIMIT ? ) as \"c\" FROM \"team\" as \"Tb\""),
  ("scalar Subquery/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"code\" as \"code\" FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"bio\" = \$1 LIMIT \$2 ) as \"c\" FROM \"team\" as \"Tb\""),
  ("scalar Subquery/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"code\" as \"code\" FROM \"driver\" as \"R1\" INNER JOIN \"profile\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driverid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_1\".\"bio\" = ? LIMIT ? ) as \"c\" FROM \"team\" as \"Tb\""),
  ("scalar Subquery/ManyToMany", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"code\" as \"code\" FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_2\".\"name\" = \$1 LIMIT \$2 ) as \"c\" FROM \"team\" as \"Tb\""),
  ("scalar Subquery/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"code\" as \"code\" FROM \"driver\" as \"R1\" INNER JOIN \"driver_sponsors\" AS \"R1_1\" ON \"R1\".\"driverid\" = \"R1_1\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"R1_2\" ON \"R1_1\".\"sponsor_sponsorid\" = \"R1_2\".\"sponsorid\" WHERE \"R1\".\"teamid\" = \"Tb\".\"teamid\" AND \"R1_2\".\"name\" = ? LIMIT ? ) as \"c\" FROM \"team\" as \"Tb\""),
  ("cjoin_on condition/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" INNER JOIN \"team\" AS \"t2\" ON (\"t2\".\"teamid\" = \"Tb\".\"teamid\") AND \"Tb_1\".\"name\" = \$1"),
  ("cjoin_on condition/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" INNER JOIN \"team\" AS \"t2\" ON (\"t2\".\"teamid\" = \"Tb\".\"teamid\") AND \"Tb_1\".\"name\" = ?"),
  ("cjoin_on condition/reverse", :postgres) =>
    (stage = :build, error = "FilterError", message = "\"results__grid\" in the ON clause of cjoin_on alias t2 crosses the reverse relation 'results'. PormG joins a path a cjoin"),
  ("cjoin_on condition/reverse", :sqlite) =>
    (stage = :build, error = "FilterError", message = "\"results__grid\" in the ON clause of cjoin_on alias t2 crosses the reverse relation 'results'. PormG joins a path a cjoin"),
  ("cjoin_on condition/reverse OneToOne", :postgres) =>
    (stage = :build, error = "FilterError", message = "\"profile__bio\" in the ON clause of cjoin_on alias t2 crosses the reverse relation 'profile'. PormG joins a path a cjoin_"),
  ("cjoin_on condition/reverse OneToOne", :sqlite) =>
    (stage = :build, error = "FilterError", message = "\"profile__bio\" in the ON clause of cjoin_on alias t2 crosses the reverse relation 'profile'. PormG joins a path a cjoin_"),
  ("cjoin_on condition/ManyToMany", :postgres) =>
    (stage = :build, error = "FilterError", message = "\"sponsors__name\" in the ON clause of cjoin_on alias t2 crosses the ManyToMany relation 'sponsors'. PormG joins a path a "),
  ("cjoin_on condition/ManyToMany", :sqlite) =>
    (stage = :build, error = "FilterError", message = "\"sponsors__name\" in the ON clause of cjoin_on alias t2 crosses the ManyToMany relation 'sponsors'. PormG joins a path a "),
  ("update()/forward nullable", :postgres) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \$2 WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = \$1) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = \$3)"),
  ("update()/forward nullable", :sqlite) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = ? WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = ?) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = ?)"),
  ("update()/reverse", :postgres) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \$2 WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"grid\" = \$1) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"grid\" = \$3)"),
  ("update()/reverse", :sqlite) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = ? WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"grid\" = ?) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"grid\" = ?)"),
  ("update()/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \$2 WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"profile\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"bio\" = \$1) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"profile\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"bio\" = \$3)"),
  ("update()/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = ? WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"profile\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"bio\" = ?) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"profile\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"bio\" = ?)"),
  ("update()/ManyToMany", :postgres) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \$2 WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver_sponsors\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_3\" ON \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" WHERE \"Tb_3\".\"name\" = \$1) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver_sponsors\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_3\" ON \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" WHERE \"Tb_3\".\"name\" = \$3)"),
  ("update()/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = ? WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver_sponsors\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_3\" ON \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" WHERE \"Tb_3\".\"name\" = ?) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver_sponsors\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_3\" ON \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" WHERE \"Tb_3\".\"name\" = ?)"),
  ("update() SET from a join/forward nullable", :postgres) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \"Tb_1\".\"number\" FROM \"driver\" AS \"Tb_1\", \"team\" AS \"Tb_2\" WHERE \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" AND \"Tb_2\".\"name\" = \$1"),
  ("update() SET from a join/forward nullable", :sqlite) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \"Tb_1\".\"number\" FROM \"driver\" AS \"Tb_1\", \"team\" AS \"Tb_2\" WHERE \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" AND \"Tb_2\".\"name\" = ?"),
  ("update() SET from a join/reverse", :postgres) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \"Tb_1\".\"number\" FROM \"driver\" AS \"Tb_1\", \"result\" AS \"Tb_2\" WHERE \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"grid\" = \$1"),
  ("update() SET from a join/reverse", :sqlite) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \"Tb_1\".\"number\" FROM \"driver\" AS \"Tb_1\", \"result\" AS \"Tb_2\" WHERE \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"grid\" = ?"),
  ("update() SET from a join/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \"Tb_1\".\"number\" FROM \"driver\" AS \"Tb_1\", \"profile\" AS \"Tb_2\" WHERE \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"bio\" = \$1"),
  ("update() SET from a join/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \"Tb_1\".\"number\" FROM \"driver\" AS \"Tb_1\", \"profile\" AS \"Tb_2\" WHERE \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" AND \"Tb_2\".\"bio\" = ?"),
  ("update() SET from a join/ManyToMany", :postgres) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \"Tb_1\".\"number\" FROM \"driver\" AS \"Tb_1\", \"driver_sponsors\" AS \"Tb_2\", \"sponsor\" AS \"Tb_3\" WHERE \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" AND \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" AND \"Tb_3\".\"name\" = \$1"),
  ("update() SET from a join/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "UPDATE \"result\" AS \"Tb\" SET \"number\" = \"Tb_1\".\"number\" FROM \"driver\" AS \"Tb_1\", \"driver_sponsors\" AS \"Tb_2\", \"sponsor\" AS \"Tb_3\" WHERE \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" AND \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" AND \"Tb_3\".\"name\" = ?"),
  ("delete()/forward nullable", :postgres) =>
    (stage = :ok, sql = "DELETE FROM \"result\" AS \"Tb\" WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = \$1) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = \$2)"),
  ("delete()/forward nullable", :sqlite) =>
    (stage = :ok, sql = "DELETE FROM \"result\" AS \"Tb\" WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = ?) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = ?)"),
  ("delete()/reverse", :postgres) =>
    (stage = :ok, sql = "DELETE FROM \"result\" AS \"Tb\" WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"grid\" = \$1) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"grid\" = \$2)"),
  ("delete()/reverse", :sqlite) =>
    (stage = :ok, sql = "DELETE FROM \"result\" AS \"Tb\" WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"grid\" = ?) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"result\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"grid\" = ?)"),
  ("delete()/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "DELETE FROM \"result\" AS \"Tb\" WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"profile\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"bio\" = \$1) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"profile\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"bio\" = \$2)"),
  ("delete()/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "DELETE FROM \"result\" AS \"Tb\" WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"profile\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"bio\" = ?) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"profile\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" WHERE \"Tb_2\".\"bio\" = ?)"),
  ("delete()/ManyToMany", :postgres) =>
    (stage = :ok, sql = "DELETE FROM \"result\" AS \"Tb\" WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver_sponsors\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_3\" ON \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" WHERE \"Tb_3\".\"name\" = \$1) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver_sponsors\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_3\" ON \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" WHERE \"Tb_3\".\"name\" = \$2)"),
  ("delete()/ManyToMany", :sqlite) =>
    (stage = :ok, sql = "DELETE FROM \"result\" AS \"Tb\" WHERE \"Tb\".\"resultid\" IN (SELECT DISTINCT \"Tb\".\"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver_sponsors\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_3\" ON \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" WHERE \"Tb_3\".\"name\" = ?) AND EXISTS (SELECT 1 FROM (SELECT 1) AS \"__pormg_anchor\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver_sponsors\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driver_driverid\" INNER JOIN \"sponsor\" AS \"Tb_3\" ON \"Tb_2\".\"sponsor_sponsorid\" = \"Tb_3\".\"sponsorid\" WHERE \"Tb_3\".\"name\" = ?)"),
  ("on() path/forward nullable", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" AND \"Tb_1\".\"name\" = \$1"),
  ("on() path/forward nullable", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" LEFT JOIN \"team\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" AND \"Tb_1\".\"name\" = ?"),
  ("on() path/reverse", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"grid\" = \$1"),
  ("on() path/reverse", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"grid\" = ?"),
  ("on() path/reverse OneToOne", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"bio\" = \$1"),
  ("on() path/reverse OneToOne", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\" FROM \"driver\" as \"Tb\" INNER JOIN \"profile\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" AND \"Tb_1\".\"bio\" = ?"),
  ("on() path/ManyToMany", :postgres) =>
    (stage = :build, error = "QueryBuildError", message = "on(\"sponsors\", …) crosses the ManyToMany relation 'sponsors', whose join goes through a link table that an ON predicate "),
  ("on() path/ManyToMany", :sqlite) =>
    (stage = :build, error = "QueryBuildError", message = "on(\"sponsors\", …) crosses the ManyToMany relation 'sponsors', whose join goes through a link table that an ON predicate "),
  ("same alias, another column projected", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"points\" as \"results__points\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = \$1"),
  ("same alias, another column projected", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"points\" as \"results__points\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"grid\" = ?"),
  ("another path to the same table projected", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"points\" as \"results__points\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" INNER JOIN \"result\" AS \"Tb_3\" ON \"Tb_2\".\"driverid\" = \"Tb_3\".\"driverid\" WHERE \"Tb_3\".\"grid\" = \$1"),
  ("another path to the same table projected", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"points\" as \"results__points\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" INNER JOIN \"driver\" AS \"Tb_2\" ON \"Tb_1\".\"driverid\" = \"Tb_2\".\"driverid\" INNER JOIN \"result\" AS \"Tb_3\" ON \"Tb_2\".\"driverid\" = \"Tb_3\".\"driverid\" WHERE \"Tb_3\".\"grid\" = ?"),
  ("order_by on a projected to-many path", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"grid\" as \"results__grid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" ORDER BY \"results__grid\" DESC NULLS FIRST"),
  ("order_by on a projected to-many path", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"driverid\" as \"driverid\", \"Tb_1\".\"grid\" as \"results__grid\" FROM \"driver\" as \"Tb\" INNER JOIN \"result\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" ORDER BY \"results__grid\" DESC NULLS FIRST"),
  ("filter, reverse then forward", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = \$1"),
  ("filter, reverse then forward", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\" FROM \"team\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\" LEFT JOIN \"team\" AS \"Tb_2\" ON \"Tb_1\".\"teamid\" = \"Tb_2\".\"teamid\" WHERE \"Tb_2\".\"name\" = ?"),
  ("filter, forward not null from Result", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"code\" = \$1"),
  ("filter, forward not null from Result", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" INNER JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"driverid\" = \"Tb_1\".\"driverid\" WHERE \"Tb_1\".\"code\" = ?"),
  ("OuterRef across a reverse path", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"number\" as \"number\" FROM \"driver\" as \"R1\" WHERE \"R1\".\"code\" = \"Tb_1\".\"code\" LIMIT \$1 ) as \"c\" FROM \"team\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\""),
  ("OuterRef across a reverse path", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"teamid\" as \"teamid\", (SELECT \"R1\".\"number\" as \"number\" FROM \"driver\" as \"R1\" WHERE \"R1\".\"code\" = \"Tb_1\".\"code\" LIMIT ? ) as \"c\" FROM \"team\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"teamid\" = \"Tb_1\".\"teamid\""),
  ("on() condition past the hop, reverse (#973)", :postgres) =>
    (stage = :call, error = "FilterError", message = "\"results__grid\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__results', past the join path 'driverid'. A "),
  ("on() condition past the hop, reverse (#973)", :sqlite) =>
    (stage = :call, error = "FilterError", message = "\"results__grid\" in on(\"driverid\", …) / cjoin(filters = …) reaches 'driverid__results', past the join path 'driverid'. A "),
  ("cjoin link unique/values", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"nationality\" as \"code__nationality\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"code\" = \"Tb_1\".\"code\""),
  ("cjoin link unique/values", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"nationality\" as \"code__nationality\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"code\" = \"Tb_1\".\"code\""),
  ("cjoin link unique/filter", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"code\" = \"Tb_1\".\"code\" WHERE \"Tb_1\".\"nationality\" = \$1"),
  ("cjoin link unique/filter", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"code\" = \"Tb_1\".\"code\" WHERE \"Tb_1\".\"nationality\" = ?"),
  ("cjoin link unique/grouped Count", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb_1\".\"nationality\" as \"code__nationality\", COUNT(\"Tb\".\"resultid\") as \"n\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"code\" = \"Tb_1\".\"code\" GROUP BY 1"),
  ("cjoin link unique/grouped Count", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb_1\".\"nationality\" as \"code__nationality\", COUNT(\"Tb\".\"resultid\") as \"n\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"code\" = \"Tb_1\".\"code\" GROUP BY 1"),
  ("cjoin link non-unique/values", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"nationality\" as \"grid__nationality\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\""),
  ("cjoin link non-unique/values", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\", \"Tb_1\".\"nationality\" as \"grid__nationality\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\""),
  ("cjoin link non-unique/filter", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" WHERE \"Tb_1\".\"nationality\" = \$1"),
  ("cjoin link non-unique/filter", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" WHERE \"Tb_1\".\"nationality\" = ?"),
  ("cjoin link non-unique/grouped Count", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb_1\".\"nationality\" as \"grid__nationality\", COUNT(\"Tb\".\"resultid\") as \"n\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" GROUP BY 1"),
  ("cjoin link non-unique/grouped Count", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb_1\".\"nationality\" as \"grid__nationality\", COUNT(\"Tb\".\"resultid\") as \"n\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" GROUP BY 1"),
  ("cjoin link non-unique/cjoin_on condition", :postgres) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"Tb_1\".\"nationality\" = \$1"),
  ("cjoin link non-unique/cjoin_on condition", :sqlite) =>
    (stage = :ok, sql = "SELECT \"Tb\".\"resultid\" as \"resultid\" FROM \"result\" as \"Tb\" LEFT JOIN \"driver\" AS \"Tb_1\" ON \"Tb\".\"grid\" = \"Tb_1\".\"number\" INNER JOIN \"driver\" AS \"d2\" ON (\"d2\".\"driverid\" = \"Tb\".\"driverid\") AND \"Tb_1\".\"nationality\" = ?"),
)
