module pending_migrations

import PormG.Migrations
import OrderedCollections: OrderedDict

# table: new_join_position
new_join_position = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS new_join_position (
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" varchar(250) NOT NULL
);""")

end
