module pending_migrations

import PormG.Migrations
import OrderedCollections: OrderedDict

# table: just_a_nested_roll_back
just_a_nested_roll_back = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS just_a_nested_roll_back (
  "test" bigint NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" varchar(250) NOT NULL
);""",
 
"New foreign key: test" =>
 """ALTER TABLE just_a_nested_roll_back ADD CONSTRAINT "just_a_nested_roll_back_test_r4waxa1r_fk" FOREIGN KEY ("test") REFERENCES "just_a_test_deletion" ("id") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on test" =>
 """CREATE INDEX IF NOT EXISTS "just_a_nested_roll_back_test_r4waxa1r_idx" ON "just_a_nested_roll_back" ("test");""")

end
