module pending_migrations

import PormG.Migrations
import OrderedCollections: OrderedDict

# table: Dim_municipio_populacao_hist
Dim_municipio_populacao_hist = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS dim_municipio_populacao_hist (
  "dcnt" integer NULL,
  "populacao" integer NOT NULL,
  "ibge" bigint NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "ano" integer NOT NULL,
  "pop_15" integer NULL
);""")

# table: Dim_servidor
Dim_servidor = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS dim_servidor (
  "host" varchar(250) NOT NULL,
  "password" varchar(250) NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nome" varchar(250) NOT NULL,
  "port" varchar(250) NOT NULL,
  "user" varchar(250) NOT NULL
);""")

# table: Dim_ibge
Dim_ibge = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS dim_ibge (
  "iso" integer NOT NULL,
  "lat" decimal(30, 6) NOT NULL,
  "regiao" varchar(30) NOT NULL,
  "uf" varchar(2) NOT NULL,
  "cod_es" integer NOT NULL,
  "regional" varchar(30) NULL,
  "lng" decimal(30, 6) NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "cidade" varchar(250) NOT NULL,
  "estado" varchar(50) NOT NULL
);""")

# table: Dim_municipio
Dim_municipio = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS dim_municipio (
  "at_ativo" boolean NOT NULL,
  "atualizacao" date NULL,
  "servidor" bigint NULL,
  "ativo" boolean NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "origem" varchar(250) NULL,
  "ibge2" integer NULL,
  "dbname" varchar(250) NULL,
  "cibge" bigint NULL,
  "base" varchar(250) NULL,
  "nome" varchar(250) NULL,
  "estado" varchar(250) NULL
);""",
 
"New foreign key: servidor" =>
 """ALTER TABLE Dim_municipio ADD CONSTRAINT "dim_municipio_servidor_2noffc7j_fk" FOREIGN KEY ("servidor") REFERENCES "dim_servidor" ("id") DEFERRABLE INITIALLY DEFERRED;""",
 
"Create index on servidor" =>
 """CREATE INDEX IF NOT EXISTS "dim_municipio_servidor_2noffc7j" ON "dim_municipio" ("servidor");""")

# table: Dim_uf
Dim_uf = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS dim_uf (
  "sigla" varchar(2) NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nome" varchar(50) NOT NULL
);""")

# table: Dim_INE_cat
Dim_INE_cat = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS dim_ine_cat (
  "tipo" varchar(50) NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nome" varchar(250) NOT NULL
);""")

# table: Dim_estabelecimento
Dim_estabelecimento = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS dim_estabelecimento (
  "publico" boolean NOT NULL,
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nome" varchar(250) NOT NULL,
  "cnes" varchar(250) NOT NULL,
  "hamigo" boolean NOT NULL
);""")

# table: Dim_tipologia
Dim_tipologia = OrderedDict{String, String}(
"New model" =>
 """CREATE TABLE IF NOT EXISTS dim_tipologia (
  "id" bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nome" varchar(50) NOT NULL,
  "abrev" varchar(50) NOT NULL
);""")

end
