name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
    # Only runs if files in these folders/files change
    paths:
      - 'docs/**'
      - 'README.md'
  pull_request:
    # Same filter for Pull Requests
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    permissions:
      contents: write
      pages: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Configure doc environment
        working-directory: ${{ github.workspace }}
        run: julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build docs
        working-directory: ${{ github.workspace }}
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate(); include("docs/make.jl")'
      - name: Deploy docs
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático do GitHub
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          DOCS_DEPLOY: 'true'
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate(); include("docs/make.jl")'